gardener/gardener-extensions

.ci/pipeline_definitions, .ci/prepare_release, hack/install-requirements.sh
Fixes #1 
Current problem is that the `prepare_release` script is always being run in the default concourse image - This is not feasible for us as this would require us to do the whole bootstrap process ourselves in the script again, leading to us having to maintain yet another 'setup'.
=> Prepare release script

controllers/os-coreos-alicloud/cmd/gardener-extension-os-coreos-alicloud/app/app.go, controllers/os-coreos-alicloud/pkg/coreos-alicloud/actuator.go, controllers/os-coreos-alicloud/pkg/coreos-alicloud/internal/templates/cloud-init.sh.template, controllers/os-coreos/cmd/gardener-extension-os-coreos/app/app.go, pkg/controller/cmd/options.go, pkg/controller/cmd/options_test.go, pkg/controller/operatingsystemconfig/controller.go
Enable `.status.units` and `status.command` for aliclouds operating system config resource.
```improvement operator
The `os-coreos-alicloud` controller does now correctly set the `.status.units` and `.status.command` fields in the `OperatingSystemConfig` resource.
```
=> Fix alicloud's status units and command

controllers/os-coreos/pkg/coreos/actuator_reconcile.go
This PR is a workaround for CVE-2019-3874. It disables the PCTP protocol on all nodes.
Currently the fix is only for the core-os controller. The core-os-alicloud controller is currently not covered with this PR and will require more time (probably 2+ weeks or unless somebody else is able to validate the fix). In the interest of security those will be submitted separately.
This is the fix for 
```noteworthy user
The CoreOS Container Linux controller does now disable the PCTP protocol on all nodes (as a workaround for CVE-2019-3874).
```
=> Black list SCTP protocol (CVE-2019-3874)

controllers/os-coreos-alicloud/pkg/coreos-alicloud/actuator_reconcile.go
DO NOT SUBMIT, NOT TESTED
This PR is a workaround for CVE-2019-3874. It disables the PCTP protocol on all nodes.
This is not yet tested due to the lack of testing environment for Alicloud (or failure to set up a working environment). It was migrated from https://github.com/gardener/gardener-extensions/pull/33 which tested ok.
```noteworthy user
The CoreOS Container Linux (Alicloud-modified) controller does now disable the PCTP protocol on all nodes (as a workaround for CVE-2019-3874).
```
=> Black list SCTP protocol for alicloud (CVE-2019-3874)

.ci/prepare_release
Fix repo path with `pushd` / `popd` for `make generate`.
```improvement operator
NONE
```
=> Fix relative repo path

.ci/pipeline_definitions, hack/generate-controller-registration.sh
This PR makes the CI pipeline execute the `prepare_release` script during its `Prepare next dev cycle` step. 
As a result all controller registration manifests will contain the next dev version which in turn will prevent future verification failures.
```improvement operator
NONE
```
=> Make CI-pipeline generate controller registrations for next dev cycle

hack/check-generate.sh, hack/clean.sh
This simplifies spotting issues discovered during `check-generate`: The generated error messages are being printed in case one of the commands fail instead of silently discarding them.
Fixes #
```improvement operator
NONE
```
=> Enhance output of `clean` and `generate` in check

controllers/os-coreos-alicloud/pkg/coreos-alicloud/internal/templates/cloud-init.sh.template, controllers/os-coreos-alicloud/pkg/coreos-alicloud/internal/testfiles/cloud-init.sh
Disable update engine service for AlicloudCoreOS
=> Disable update engine service for AlicloudCoreOS

hack/generate-controller-registration.sh, hack/install-requirements.sh
This PR makes the `generate-controller-registration.sh` to fail whenever there is an error (also considers pipe failures).
```improvement operator
NONE
```
=> Improve generate script and local dev experience

hack/install-requirements.sh
fix `uname -s` based check emitting the macos warning
also, properly pin helm & helm installer script version.
Fixes #60 
```improvement operator
NONE
```
=> Fix install-requirements.sh MacOs warning

controllers/provider-aws/pkg/webhook/controlplane/mutator.go, controllers/provider-aws/pkg/webhook/controlplane/mutator_test.go, controllers/provider-aws/pkg/webhook/controlplaneexposure/mutator.go, controllers/provider-aws/pkg/webhook/controlplaneexposure/mutator_test.go, pkg/webhook/controlplane/test/matchers.go, pkg/webhook/controlplane/utils.go
Adds tests for the actual implementation of AWS controlplane webhooks.
Based on #52, which should be merged first. Tests for the generic part of the controlplane webhooks introduced with #48 will follow in another PR.
```improvement operator
Add AWS controlplane webhooks tests
```
=> Add AWS controlplane webhooks tests

controllers/provider-gcp/pkg/controller/infrastructure/actuator_delete.go, controllers/provider-gcp/pkg/internal/infrastructure/infrastructure.go, controllers/provider-gcp/pkg/internal/infrastructure/infrastructure_test.go
Length of route names are hardly set to 26 in the gce cloudprovider implementation. Therefore compare for  "shoot--" prefix and network name during route cleanup.
```improvement operator
Cleanup route names by network name and "shoot--" prefix
```
=> Constrain route names

controllers/provider-gcp/pkg/internal/infrastructure/infrastructure.go
Fix comparison of networks during route deletion
```improvement operator
NONE
```
=> Fix comparison of networks during route deletion

controllers/provider-aws/charts/images.yaml, controllers/provider-azure/charts/images.yaml, controllers/provider-gcp/charts/images.yaml, controllers/provider-openstack/charts/images.yaml, controllers/provider-packet/charts/images.yaml
``` improvement operator github.com/gardener/machine-controller-manager #271 @rfranzke
The machine-controller-manager does now correctly add its finalizer to Alicloud machine class secrets.
```
``` noteworthy user github.com/gardener/machine-controller-manager #268 @prashanth26
Deletion of annotations, labels and taints are now supported
```
``` improvement operator github.com/gardener/machine-controller-manager #268 @prashanth26
Multiple taints with the same key but different values are now supported
```
``` improvement operator github.com/gardener/machine-controller-manager #265 @hardikdr
Bugfix: Existing machine-objects now adopts the node-label.
```
``` improvement operator github.com/gardener/machine-controller-manager #264 @prashanth26
Bugfix: MachineDeployment with …
```
=> [ci:component:github.com/gardener/machine-controller-manager:0.16.0->0.18.0]

controllers/extension-certificate-service/charts/internal/cert-broker/templates/deployment.yaml, controllers/extension-certificate-service/charts/internal/cert-manager/values.yaml, controllers/provider-alicloud/charts/internal/machine-controller-manager/seed/templates/deployment.yaml, controllers/provider-aws/charts/internal/cloud-controller-manager/templates/cloud-controller-manager.yaml, controllers/provider-aws/charts/internal/machine-controller-manager/seed/templates/deployment.yaml, controllers/provider-azure/charts/internal/cloud-controller-manager/templates/cloud-controller-manager.yaml, controllers/provider-azure/charts/internal/machine-controller-manager/seed/templates/deployment.yaml, controllers/provider-gcp/charts/internal/cloud-controller-manager/templates/cloud-controller-manager.yaml, controllers/provider-gcp/charts/internal/machine-controller-manager/seed/templates/deployment.yaml, controllers/provider-openstack/charts/internal/machine-controller-manager/seed/templates/deployment.yaml, controllers/provider-packet/charts/internal/cloud-controller-manager/templates/cloud-controller-manager.yaml, controllers/provider-packet/charts/internal/machine-controller-manager/seed/templates/deployment.yaml, vendor/github.com/gardener/gardener/pkg/operation/terraformer/terraformer.go
Network policies are going to be added in https://github.com/gardener/gardener/pull/904 blocking all egress and ingress traffic. This PR is a prerequisite for that.
n/a
There is a little chicken and egg problem - the https://github.com/gardener/gardener/pull/904 PR must be merged in order to update the terraformer with correct labels, but it cannot be merged, because extension controllers don't use the annotations and it'll break the cluster creation.
/cc @timuthy @deitch @stoyanr @jia-jerry
```improvement operator
NetworkPolicy labels are added to all components deployed in a Shoot namespace.
```
=> Add network policies

controllers/extension-certificate-service/pkg/controller/certservice/actuator.go
This PR fixes an issue for the `Certificate-Service` extension controller when the `domain` of a shoot is nil. This is a valid scenario if the shoot's dns provider is `unmanaged`. Hence, the extension controller can omit the deployment of `Cert-Broker`.
```improvement operator
Fixes an issue for the `Certificate-Service` controller which couldn't handle shoots whose dns provider was `unmanaged`.
```
=> Skip Cert-Broker when DNS provider is unmanaged

controllers/provider-gcp/pkg/webhook/controlplane/ensurer.go, controllers/provider-gcp/pkg/webhook/controlplane/ensurer_test.go
Reading `/etc/hostname` is the canonical way of getting the static hostname of a machine.
n/a
See https://github.com/gardener/gardener/pull/1077
```improvement operator
GCP: `kubelet.service` now reads from `/etc/hostname` for hostname override.
```
=> Use `etc/hostname` for hostname override.

controllers/provider-openstack/pkg/apis/openstack/types_controlplane.go, controllers/provider-openstack/pkg/apis/openstack/v1alpha1/types_controlplane.go, controllers/provider-openstack/pkg/apis/openstack/v1alpha1/zz_generated.conversion.go, controllers/provider-openstack/pkg/apis/openstack/v1alpha1/zz_generated.deepcopy.go, controllers/provider-openstack/pkg/apis/openstack/zz_generated.deepcopy.go, controllers/provider-openstack/pkg/controller/controlplane/valuesprovider.go, controllers/provider-openstack/pkg/controller/controlplane/valuesprovider_test.go
Read `DHCPDomain` and `RequestTimeout` from the CloudProfile instead of ControlPlaneConfig in OpenStack ControlPlane controller
Fixes #117 
```improvement operator
Read `DHCPDomain` and `RequestTimeout` from the CloudProfile in OpenStack ControlPlane controller
```
=> Fix OpenStack ControlPlane controller's values

pkg/controller/controlplane/genericactuator/actuator.go, pkg/controller/controlplane/genericactuator/actuator_test.go
Temporarily disables writing to shoot in controlplane controllers to resolve ordering issue in Gardener flow.
* The issue and a proposed approach for solving it is described in #111.
* Code is intentionally commented out, not deleted, as it will be needed soon to implement a more permanent solutions to the issue.
* Depends on #107 which should be merged first.
```improvement operator
Temporarily disable writing to shoot in controlplane controllers
```
=> Temporarily disable writing to shoot in controlplane controllers

controllers/provider-alicloud/pkg/webhook/controlplaneexposure/ensurer.go, controllers/provider-alicloud/pkg/webhook/controlplaneexposure/ensurer_test.go, controllers/provider-aws/pkg/webhook/controlplaneexposure/ensurer.go, controllers/provider-aws/pkg/webhook/controlplaneexposure/ensurer_test.go, controllers/provider-azure/pkg/webhook/controlplaneexposure/ensurer.go, controllers/provider-azure/pkg/webhook/controlplaneexposure/ensurer_test.go, controllers/provider-gcp/pkg/webhook/controlplaneexposure/ensurer.go, controllers/provider-gcp/pkg/webhook/controlplaneexposure/ensurer_test.go, controllers/provider-openstack/pkg/webhook/controlplaneexposure/ensurer.go, controllers/provider-openstack/pkg/webhook/controlplaneexposure/ensurer_test.go, pkg/webhook/controlplane/etcd.go
The name has recently changed in Gardener due to etcd migration and needs to be reflected here in the extension controllers as well.
Fixes #116
FYI @mkoynov 
```improvement operator
NONE
```
=> Fix etcd-main PVC template name based on latest Gardener changes

controllers/provider-alicloud/charts/images.yaml, controllers/provider-aws/charts/images.yaml, controllers/provider-azure/charts/images.yaml, controllers/provider-gcp/charts/images.yaml, controllers/provider-openstack/charts/images.yaml
``` improvement user github.com/gardener/etcd-backup-restore #166 @swapnilgm
In the case that initial delta snapshot fails, a full snapshot is tried instead.
```
=> [ci:component:github.com/gardener/etcd-backup-restore:0.6.3->0.6.4]

controllers/provider-alicloud/pkg/webhook/controlplanebackup/ensurer.go, controllers/provider-alicloud/pkg/webhook/controlplanebackup/ensurer_test.go, controllers/provider-aws/pkg/webhook/controlplane/ensurer.go, controllers/provider-aws/pkg/webhook/controlplane/ensurer_test.go, controllers/provider-aws/pkg/webhook/controlplanebackup/ensurer.go, controllers/provider-aws/pkg/webhook/controlplanebackup/ensurer_test.go, controllers/provider-azure/pkg/webhook/controlplane/ensurer.go, controllers/provider-azure/pkg/webhook/controlplane/ensurer_test.go, controllers/provider-azure/pkg/webhook/controlplanebackup/ensurer.go, controllers/provider-azure/pkg/webhook/controlplanebackup/ensurer_test.go, controllers/provider-gcp/pkg/webhook/controlplane/ensurer.go, controllers/provider-gcp/pkg/webhook/controlplane/ensurer_test.go, controllers/provider-gcp/pkg/webhook/controlplanebackup/ensurer.go, controllers/provider-gcp/pkg/webhook/controlplanebackup/ensurer_test.go, controllers/provider-openstack/pkg/webhook/controlplane/ensurer.go, controllers/provider-openstack/pkg/webhook/controlplane/ensurer_test.go, controllers/provider-openstack/pkg/webhook/controlplanebackup/ensurer.go, controllers/provider-openstack/pkg/webhook/controlplanebackup/ensurer_test.go, pkg/controller/controlplane/genericactuator/actuator.go, pkg/webhook/controlplane/checksums.go
Controlplane webhooks now add checksum annotations for all secrets / configmaps that are being mounted as volumes or used as a source of env vars.
Fixes #115 
It also removes some volumes mounted by controlplane webhooks that are actually not needed.
```improvement operator
NONE
```
=> Add checksum annotations in controlplane webhooks

controllers/provider-alicloud/pkg/webhook/controlplanebackup/ensurer.go, controllers/provider-alicloud/pkg/webhook/controlplanebackup/ensurer_test.go, controllers/provider-aws/pkg/webhook/controlplanebackup/ensurer.go, controllers/provider-aws/pkg/webhook/controlplanebackup/ensurer_test.go, controllers/provider-azure/pkg/webhook/controlplanebackup/ensurer.go, controllers/provider-azure/pkg/webhook/controlplanebackup/ensurer_test.go, controllers/provider-gcp/pkg/webhook/controlplanebackup/ensurer.go, controllers/provider-gcp/pkg/webhook/controlplanebackup/ensurer_test.go, controllers/provider-openstack/pkg/webhook/controlplanebackup/ensurer.go, controllers/provider-openstack/pkg/webhook/controlplanebackup/ensurer_test.go, pkg/webhook/controlplane/etcd.go
Fixes volume claim template name in etcd backup container volume mounts
Depends on #127 which should be merged first.
```improvement operator
NONE
```
=> Fix volume claim template name

controllers/provider-alicloud/cmd/gardener-extension-provider-alicloud/app/app.go, controllers/provider-aws/cmd/gardener-extension-provider-aws/app/app.go, controllers/provider-azure/cmd/gardener-extension-provider-azure/app/app.go, controllers/provider-gcp/cmd/gardener-extension-provider-gcp/app/app.go, controllers/provider-openstack/cmd/gardener-extension-provider-openstack/app/app.go, controllers/provider-packet/cmd/gardener-extension-provider-packet/app/app.go, pkg/controller/worker/genericactuator/actuator_reconcile.go, pkg/controller/worker/machine_crds.go, pkg/controller/worker/options.go
Ensure worker CRDs conditionally at startup to prevent REST mapping issues and not recreate them in every reconciliation loop.
```noteworthy operator
All provider controllers do now have a new flag `--worker-deploy-crds` which defaults to `true`. If enabled then all worker-relevant CRDs like `MachineDeployment`, etc. will be deployed during startup time of the controller.
```
=> Ensure worker CRDs conditionally at startup

controllers/provider-alicloud/charts/images.yaml, controllers/provider-aws/charts/images.yaml, controllers/provider-azure/charts/images.yaml, controllers/provider-gcp/charts/images.yaml, controllers/provider-openstack/charts/images.yaml, controllers/provider-packet/charts/images.yaml
``` noteworthy operator github.com/gardener/terraformer $157bce76c33d1d2ab95b28822be61f0edf300e63
The Terraform version has been upgraded to `0.11.14`.
```
=> [ci:component:github.com/gardener/terraformer:0.12.0->0.13.0]

controllers/provider-gcp/pkg/internal/infrastructure/infrastructure.go
Delete firewall rules with ```shoot--``` prefix, which sometime remain and block infrastructure deletion on gcp.
```improvement operator
None
```
=> Delete fw rules with shoot prefix

controllers/provider-azure/pkg/azure/types.go, controllers/provider-azure/pkg/webhook/controlplane/ensurer.go, controllers/provider-azure/pkg/webhook/controlplane/ensurer_test.go, controllers/provider-openstack/pkg/openstack/types.go, controllers/provider-openstack/pkg/webhook/controlplane/ensurer.go, controllers/provider-openstack/pkg/webhook/controlplane/ensurer_test.go, pkg/mock/gardener-extensions/webhook/controlplane/genericmutator/mocks.go, pkg/webhook/controlplane/genericmutator/mutator.go, pkg/webhook/controlplane/genericmutator/mutator_test.go, pkg/webhook/controlplane/genericmutator/noopensurer.go
* Ensure Kubelet Service unit option `ExecStartPre` (CloudConfigUserDataConfig.HostnameOverride)
* Ensure Cloud provider config as part of kubelet configuration
```improvement operator
Issues related to Openstack and Azure extension controller
```
=> Ensure Cloud provider config as part of kubelet configuration

controllers/provider-aws/pkg/webhook/controlplane/ensurer.go, controllers/provider-aws/pkg/webhook/controlplane/ensurer_test.go, controllers/provider-gcp/pkg/webhook/controlplane/ensurer.go, controllers/provider-gcp/pkg/webhook/controlplane/ensurer_test.go
EnsureKubernetesGeneralConfiguration() function in GCP and AWS always applied the needed kubernetes configuration despite the fact that it can be there already. 
```improvement operator
Fix Ensuring kubernetes general configuration for AWS and GCP
```
=> Fix Ensuring kubernetes general configuration for AWS and GCP

controllers/provider-alicloud/pkg/controller/controlplane/valuesprovider.go, controllers/provider-alicloud/pkg/controller/controlplane/valuesprovider_test.go, controllers/provider-aws/pkg/controller/controlplane/valuesprovider.go, controllers/provider-aws/pkg/controller/controlplane/valuesprovider_test.go, controllers/provider-azure/pkg/controller/controlplane/valuesprovider.go, controllers/provider-azure/pkg/controller/controlplane/valuesprovider_test.go, controllers/provider-gcp/pkg/controller/controlplane/valuesprovider.go, controllers/provider-gcp/pkg/controller/controlplane/valuesprovider_test.go, controllers/provider-openstack/pkg/controller/controlplane/valuesprovider.go, controllers/provider-openstack/pkg/controller/controlplane/valuesprovider_test.go, controllers/provider-packet/pkg/controller/controlplane/valuesprovider.go, controllers/provider-packet/pkg/controller/controlplane/valuesprovider_test.go, pkg/controller/controlplane/actuator.go, pkg/controller/controlplane/genericactuator/actuator.go, pkg/controller/controlplane/genericactuator/actuator_test.go, pkg/controller/controlplane/reconciler.go, pkg/controller/shoot.go, pkg/mock/gardener-extensions/controller/controlplane/genericactuator/mocks.go
Fixes a controlplane hibernation issue on Alicloud and all providers after 1.14
When the shoot is hibernated, the controlplane controllers scale down the CCM only if kube-apiserver is already scaled down, and requeue the `ControlPlane` resource until this condition holds true.
```improvement operator
NONE
```
=> Fix controlplane hibernation issue

controllers/provider-azure/pkg/webhook/controlplane/ensurer.go, controllers/provider-azure/pkg/webhook/controlplane/ensurer_test.go, controllers/provider-openstack/pkg/webhook/controlplane/ensurer.go, controllers/provider-openstack/pkg/webhook/controlplane/ensurer_test.go
In case the deletion of shoot has been triggered, the controlplane webhook is trying to reconcile the OperatingSystemConfig, but some of the resources are already deleted. This leads to constant loop.
This behaviour is found in Openstack and Azure extension providers
```improvement operator
Fix Openstack/Azure controlplane ensurer when deleting shoot
```
=> Fix Openstack/Azure controlplane ensurer in deletion context

controllers/provider-alicloud/charts/images.yaml, controllers/provider-aws/charts/images.yaml, controllers/provider-azure/charts/images.yaml, controllers/provider-gcp/charts/images.yaml, controllers/provider-openstack/charts/images.yaml, controllers/provider-packet/charts/images.yaml
``` improvement operator github.com/gardener/machine-controller-manager #279 @amshuman-kr
Fix panic in AWS driver if AMI not found.
```
``` improvement operator github.com/gardener/machine-controller-manager #273 @deitch
Fixes packet driver
```
``` noteworthy operator github.com/gardener/machine-controller-manager #261 @prashanth26
Update Azure SDK from 12.5-beta to 26.1
```
``` improvement operator github.com/gardener/machine-controller-manager #261 @prashanth26
Ensure 'x-ms-request-id' header is logged in case of Azure API failures.
```
``` noteworthy user github.com/gardener/machine-controller-manager #261 @prashanth26
Orphan VMs/disks/NICs handler has been fixed
```
=> [ci:component:github.com/gardener/machine-controller-manager:0.18.0->0.19.0]

controllers/provider-alicloud/pkg/webhook/controlplane/ensurer.go, controllers/provider-packet/pkg/webhook/controlplane/ensurer.go, pkg/webhook/controlplane/utils.go
Fixes a possible bug/Makes it easier to read when there is need to ensure an element in a string list with no elements to remove a leading comma.
Removes duplication elements with wrong value for the command line arg "--feature-gates=" in the kube apiserver for packet and alicloud providers.
```improvement operator
NONE
```
=> Fix contains string with prefix bug

.ci/component_descriptor
Controllers are independent components. They are currently grouped in
one common repository temporarily for pragmatic reasons (planned to be
split into multiple repositories "soon").
For the time being, include component names into logical image names so
that the declaring component is expressed in the `component_descriptor`
emitted from release builds.
=> Qualify image names

controllers/provider-aws/charts/internal/cloud-controller-manager/values.yaml, controllers/provider-azure/charts/internal/cloud-controller-manager/values.yaml, controllers/provider-gcp/charts/internal/cloud-controller-manager/values.yaml
In order to better utilize the Seed nodes and thus also save costs, the pods of the Shoot control plane should only request the resources they really need.
Based on the evaluation of the VPA recommendations for all Shoots on our Canary and Live landscape over a few weeks, the new values reflects the average CPU and memory recommendations for the cloud controller manager pod.
Fixes #
```NONE```
=> Adapt CCM pod requests based on VPA recommendations

pkg/webhook/controlplane/etcd.go
In order to better utilize the Seed nodes, the pods of the Shoot control plane should only request the resources they really need.
Based on the evaluation of the VPA recommendations for all Shoots on our Canary and Live landscape over a few weeks, the new value reflects the maximum recommendation for the ETCD backup-restore container.
This maximum value also ensures that the ETCD pods aren't evicted from a node at normal scenarios because of exhausted node resources.
Fixes #
@swapnilgm 
```
NONE
```
=> Adapt requests for etcd backup-restore sidecar based on VPA recommendations

.github/pull_request_template.md
This PR adds the `developer` target group
Fixes #
`developer` target group was introduced with https://github.com/gardener/cc-utils/pull/303
```improvement operator
NONE
```
=> PR-Template: add developer target group

Gopkg.lock, Gopkg.toml, vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types_network.go
Trying locally `dep ensure -v` was failing with:
```
$ dep ensure -v
[...]
Solving failure: No versions of github.com/gardener/gardener met constraints:
0fe4fccadc48e62b6f7d7a4a6965dfa369f90531: unable to update checked out version: fatal: reference is not a tree: 0fe4fccadc48e62b6f7d7a4a6965dfa369f90531
: command failed: [git checkout 0fe4fccadc48e62b6f7d7a4a6965dfa369f90531]: exit status 128
```
On a newly cloned g/gardener:
```
git read-tree 0fe4fccadc48e62b6f7d7a4a6965dfa369f90531
fatal: failed to unpack tree object 0fe4fccadc48e62b6f7d7a4a6965dfa369f90531
```
I changed the revision to point https://github.com/gardener/gardener/commit/641367fd36d54086712027f337effcb6c9f950cf (on branch `gardener-extension-fixes`).
**Which issue(s) this PR …
=> Fix dep ensure

controllers/provider-alicloud/charts/images.yaml
Remove runtimeVersion specification in image lists of alicloud where runtimeVersion is not 1.13.x. Doing this avoids adding new specifically versioned items in images.yaml at the time of version update (every version shares the same image specification if it does not require a specific version of image).
None.
```improvement operator
The provider extension controllers for Alicloud do now support Kubernetes v1.15.0.
```
=> remove runtimeVersion (>= 1.14.x) specification for alicloud

controllers/provider-openstack/pkg/controller/controlplane/add.go, controllers/provider-openstack/pkg/controller/controlplane/wrapper.go
This PR adds a 4 minute delay before removing the OpenStack control plane. That way we give the `cloud-controller-manager` enough time to properly cleanup services with their corresponding load balancer instances.
Needed due to #161 
This is just a temporary fix to mitigate the issues we are currently experiencing. Should be refactored in the future.
```improvement operator
Added a 4 minutes delay before removing OpenStack cloud controller manager
```
=> Added delay before removing OpenStack cloud controller manager

controllers/provider-azure/charts/internal/cloud-provider-config/templates/azure-credentials.tpl, controllers/provider-azure/charts/internal/cloud-provider-config/templates/cloud-provider-config.tpl, controllers/provider-azure/charts/internal/cloud-provider-config/templates/cloud-provider-config.yaml, controllers/provider-azure/charts/internal/cloud-provider-config/templates/cloud-provider-worker-config.yaml, controllers/provider-azure/pkg/azure/types.go, controllers/provider-azure/pkg/controller/controlplane/valuesprovider.go, controllers/provider-azure/pkg/webhook/controlplane/ensurer.go, controllers/provider-azure/pkg/webhook/controlplane/ensurer_test.go
Remove Azure credentials from cloud-config for 1.15 as they are not needed anymore. For more informtaion, please refer to: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#azure 
```noteworthy operator
Azure cloud-config no longer requires credentials. 
```
=> Create Credentialless Cloud-Config for Azure Workers

Gopkg.lock, Gopkg.toml, controllers/extension-certificate-service/cmd/main.go, controllers/hyper/cmd/gardener-extension-hyper/main.go, controllers/os-coreos-alicloud/cmd/gardener-extension-os-coreos-alicloud/main.go, controllers/os-coreos/cmd/gardener-extension-os-coreos/main.go, controllers/os-suse-jeos/cmd/gardener-extension-os-suse-jeos/main.go, controllers/os-ubuntu/cmd/gardener-extension-os-ubuntu/main.go, controllers/provider-alicloud/cmd/gardener-extension-provider-alicloud/main.go, controllers/provider-aws/cmd/gardener-extension-provider-aws/main.go, controllers/provider-azure/cmd/gardener-extension-provider-azure/main.go, controllers/provider-gcp/cmd/gardener-extension-provider-gcp/main.go, controllers/provider-openstack/cmd/gardener-extension-provider-openstack/main.go, controllers/provider-packet/cmd/gardener-extension-provider-packet/main.go, pkg/controller/worker/genericactuator/actuator_delete.go, pkg/controller/worker/genericactuator/actuator_reconcile.go, pkg/controller/worker/genericactuator/machine_controller_manager.go, pkg/log/log.go
This PR (re)deploys MCM when when `Worker` resources are deleted. This is a precaution to ensure that existing worker nodes are deleted properly.
/cc @DockToFuture 
The timestamp in the controller logs have been adjusted to a human readable format.
```improvement operator
The worker actuator does now re-apply the `machine-controller-manager` deployment during worker deletion to ensure a proper worker node deletion.
```
=> Deploy MCM during Worker deletion

controllers/provider-alicloud/charts/internal/machine-controller-manager/seed/templates/deployment.yaml, controllers/provider-alicloud/charts/internal/machine-controller-manager/shoot/templates/clusterrole-machine-controller-manager.yaml, controllers/provider-aws/charts/internal/machine-controller-manager/seed/templates/deployment.yaml, controllers/provider-aws/charts/internal/machine-controller-manager/shoot/templates/clusterrole-machine-controller-manager.yaml, controllers/provider-azure/charts/internal/machine-controller-manager/seed/templates/deployment.yaml, controllers/provider-azure/charts/internal/machine-controller-manager/shoot/templates/clusterrole-machine-controller-manager.yaml, controllers/provider-gcp/charts/internal/machine-controller-manager/seed/templates/deployment.yaml, controllers/provider-gcp/charts/internal/machine-controller-manager/shoot/templates/clusterrole-machine-controller-manager.yaml, controllers/provider-openstack/charts/internal/machine-controller-manager/seed/templates/deployment.yaml, controllers/provider-openstack/charts/internal/machine-controller-manager/shoot/templates/clusterrole-machine-controller-manager.yaml, controllers/provider-packet/charts/internal/machine-controller-manager/seed/templates/deployment.yaml, controllers/provider-packet/charts/internal/machine-controller-manager/shoot/templates/clusterrole-machine-controller-manager.yaml
- Updates MCM shoot `clusterRoles` to allow access to `PV` and `PVC` resources
- Updates worst case `machine-drain-timeout` to `12hrs`
Fixes #
Hold merging of PR until new MCM is released.
```improvement developer
Updates MCM ClusterRole for shoot to allow access to PV and PVC resources
```
```improvement user
Updates worst-case `machine-drain-timeout` to `12hrs`
```
=> Updated charts to support for MCM version 0.20.0

controllers/provider-alicloud/charts/images.yaml, controllers/provider-aws/charts/images.yaml, controllers/provider-azure/charts/images.yaml, controllers/provider-gcp/charts/images.yaml, controllers/provider-openstack/charts/images.yaml, controllers/provider-packet/charts/images.yaml
``` noteworthy operator github.com/gardener/machine-controller-manager #288 @amshuman-kr
Changes the drain logic to honour the individual `pods`' `terminationGracePeriodSeconds` instead of a fixed(though configurable) `timeout`. For the `pods` without volumes, the timeout would be a bit longer than the maximum of `terminationGracePeriodSeconds` of the `pods` without volume. For the `pods` with volumes, the timeout is its own `terminationGracePeriodSeconds` and a **fixed** (but configurable) volume detach timeout for each pod.
The command-line flags `machine-max-evict-retries` and `machine-pv-detach-timeout` can be used to customize the default behaviour of the number of retries for eviction and wait period for the detaching of volumes after pods are evicted/deleted.
The …
```
=> [ci:component:github.com/gardener/machine-controller-manager:0.19.0->0.20.0]

controllers/provider-aws/pkg/webhook/controlplane/ensurer.go, controllers/provider-aws/pkg/webhook/controlplane/ensurer_test.go
So far we were using only CoreOS which has by default hostname set to FQDN.
With Ubuntu and JeOS this is not the case and it causes issues with the AWS services.
Fixes #
/cc @pablochacin @timuthy @rfranzke 
```improvement user
`provider-aws` sets the hostname of the VMs to be their FQDN.
```
=> Set hostname on AWS VMs to be the FQDN

controllers/provider-alicloud/charts/images.yaml, controllers/provider-aws/charts/images.yaml, controllers/provider-azure/charts/images.yaml, controllers/provider-gcp/charts/images.yaml, controllers/provider-openstack/charts/images.yaml, controllers/provider-packet/charts/images.yaml
``` improvement operator github.com/gardener/machine-controller-manager #301 @prashanth26
Bugfix: Allows force deletion of pods who have no controllers backing them
```
``` noteworthy operator github.com/gardener/machine-controller-manager #288 @amshuman-kr
Changes the drain logic to honour the individual `pods`' `terminationGracePeriodSeconds` instead of a fixed(though configurable) `timeout`. For the `pods` without volumes, the timeout would be a bit longer than the maximum of `terminationGracePeriodSeconds` of the `pods` without volume. For the `pods` with volumes, the timeout is its own `terminationGracePeriodSeconds` and a **fixed** (but configurable) volume detach timeout for each pod.
The command-line flags `machine-max-evict-retries` and …
```
=> [ci:component:github.com/gardener/machine-controller-manager:0.19.0->0.20.1]

controllers/provider-alicloud/charts/internal/shoot-system-components/charts/csi-alicloud/templates/csi-diskplugin-ds.yaml
Remove redundant security context flags for CSI plugin for AliCloud
Fixes #
Priviliged option is in god mode. Don't need other security context flags.
```improvement operator
```
=> Remove redundant security context flags for CSI plugin for AliCloud

controllers/provider-alicloud/charts/images.yaml, controllers/provider-aws/charts/images.yaml, controllers/provider-azure/charts/images.yaml, controllers/provider-gcp/charts/images.yaml, controllers/provider-openstack/charts/images.yaml, controllers/provider-packet/charts/images.yaml
``` improvement operator github.com/gardener/etcd-backup-restore #184 @swapnilgm
Added new flag `experimental-fail-below-revision` flag for initializer and `/initialization/start` http call
```
``` improvement operator github.com/gardener/etcd-backup-restore #182 @amshuman-kr
The health status changes are now logged at `INFO` level to help debug issues with etcd readiness.
```
``` improvement user github.com/gardener/etcd-backup-restore #180 @shreyas-s-rao
All exposed metrics are initialised to zero values.
```
``` improvement operator github.com/gardener/etcd-backup-restore #176 @kayrus
Etcd-backup-restore now uses the go modules for its dependecy management.
```
``` improvement operator github.com/gardener/etcd-backup-restore #172 @shreyas-s-rao
Fixed liveness probe …
```
=> [ci:component:github.com/gardener/etcd-backup-restore:0.6.4->0.7.0]

pkg/controller/controlplane/genericactuator/actuator.go, pkg/controller/controlplane/reconciler.go, pkg/controller/shoot.go
After #178 the provider-specific control plane components are no longer woken up when a hibernated shoot is deleted. This PR fixes this.
/cc @timuthy 
```improvement operator
The generic control plane actuator does now correctly wake up provider-specific control plane components when a hibernated shoot is deleted.
```
=> Ensure wake-up of provider specific components when hibernated shoot is deleted

controllers/provider-azure/example/20-crd-network.yaml, extensions.yaml
- Add Network CRD to provider-azure/examples.
- Add `controllers/networking-calico` to `extensions.yaml`.
Fixes #
```improvement operator
NONE
```
=> Add Network CRD to provider-azure/examples

controllers/provider-aws/charts/internal/aws-lb-readvertiser/templates/aws-lb-readvertiser-vpa.yaml, controllers/provider-aws/pkg/controller/controlplane/valuesprovider.go
Adds aws-lb-readvertiser-vpa chart to provider-aws controller
Fixes #233 
```improvement operator
Add aws-lb-readvertiser-vpa to provider-aws
```
=> Add aws-lb-readvertiser-vpa to AWS

hack/install-requirements.sh
Add export also for gnu-tar in `hack/install-requirements.sh`.
/kind flake
Fixes #
```improvement operator
NONE
```
=> Add export also for gnu-tar in hack/install-requirements.sh

controllers/provider-aws/pkg/controller/worker/machines.go, controllers/provider-aws/pkg/controller/worker/machines_test.go
Currently the <Provider>MachineClass secrets cleanup logic fetches all secrets using the label selector `garden.sapcloud.io/purpose=machineclass`. provider-aws was no adding this label to the secrets.
The PR adds this label to the machine class secrets to enable their cleanup. 
/kind bug
Fixes #272
```improvement operator
The AWS extension controller now properly cleans up machine class secrets that are no longer used.
```
=> Fix MachineClass secrets cleanup for provider-aws

pkg/controller/controlplane/genericactuator/actuator.go
ignore `NotFound` errors when deleting a `ControlPlane` resource.
```improvement operator
The generic control plane actuator does now ignore `NotFound` errors during deletion.
```
=> ignore `NotFound` errors when deleting a `ControlPlane` resource

controllers/provider-alicloud/charts/images.yaml, controllers/provider-aws/charts/images.yaml, controllers/provider-azure/charts/images.yaml, controllers/provider-gcp/charts/images.yaml, controllers/provider-openstack/charts/images.yaml, controllers/provider-packet/charts/images.yaml
``` noteworthy user github.com/gardener/machine-controller-manager #320 @prashanth26
Fixes issues while draining nodes in unknown state.
```
``` improvement user github.com/gardener/machine-controller-manager #320 @prashanth26
Fixes issues while overriding termination grace periods for pods with larger values.
```
``` noteworthy operator github.com/gardener/machine-controller-manager #319 @hardikdr
Fixes consistency issues with machine-deployments, machine-classes, and secrets.
```
``` improvement operator github.com/gardener/machine-controller-manager #319 @hardikdr
Better error handling while adding/removing the finalizers on machine classes & secrets.
```
``` improvement operator github.com/gardener/machine-controller-manager #319 @hardikdr
Re-enqueues the machine …
```
=> [ci:component:github.com/gardener/machine-controller-manager:0.20.1->0.21.0]

controllers/provider-alicloud/charts/internal/machine-controller-manager/seed/templates/deployment.yaml, controllers/provider-aws/charts/internal/machine-controller-manager/seed/templates/deployment.yaml, controllers/provider-azure/charts/internal/machine-controller-manager/seed/templates/deployment.yaml, controllers/provider-gcp/charts/internal/machine-controller-manager/seed/templates/deployment.yaml, controllers/provider-openstack/charts/internal/machine-controller-manager/seed/templates/deployment.yaml, controllers/provider-packet/charts/internal/machine-controller-manager/seed/templates/deployment.yaml
- We need more logs for debugging MCM with issues. 
- Changes
- Reduced drain timeouts to `2hrs`
- Increase log level for MCM to `v=3`
Fixes #
```improvement operator
Reduced maximum drain timeout for a machine in MCM to 2hrs
```
=> Updated timeout and log levels for MCM

controllers/provider-alicloud/charts/images.yaml, controllers/provider-aws/charts/images.yaml, controllers/provider-azure/charts/images.yaml, controllers/provider-gcp/charts/images.yaml, controllers/provider-openstack/charts/images.yaml, controllers/provider-packet/charts/images.yaml
``` improvement operator github.com/gardener/etcd-backup-restore #191 @swapnilgm
[Fix] Cleanup in-memory events before stopping snapshotter.
```
=> [ci:component:github.com/gardener/etcd-backup-restore:0.7.0->0.7.1]

controllers/provider-aws/pkg/aws/client/client.go
Fixes #
```improvement operator
```
=> [fix] Ignore us-east-1 location constraint in backup bucket creation

controllers/provider-alicloud/charts/images.yaml, controllers/provider-aws/charts/images.yaml, controllers/provider-azure/charts/images.yaml, controllers/provider-gcp/charts/images.yaml, controllers/provider-openstack/charts/images.yaml, controllers/provider-packet/charts/images.yaml
``` improvement operator github.com/gardener/etcd-backup-restore #198 @swapnilgm
Fix the object listing for OSS snapstore.
```
=> [ci:component:github.com/gardener/etcd-backup-restore:0.7.1->0.7.2]

controllers/provider-alicloud/charts/images.yaml, controllers/provider-aws/charts/images.yaml, controllers/provider-azure/charts/images.yaml, controllers/provider-gcp/charts/images.yaml, controllers/provider-openstack/charts/images.yaml, controllers/provider-packet/charts/images.yaml
``` improvement developer github.com/gardener/etcd-backup-restore #199 @shreyas-s-rao
Expose new metric `etcdbr_snapshot_required`.
```
=> [ci:component:github.com/gardener/etcd-backup-restore:0.7.2->0.7.3]

controllers/provider-azure/charts/internal/cloud-provider-config/templates/cloud-provider-config.tpl, controllers/provider-azure/charts/internal/cloud-provider-config/values.yaml, controllers/provider-azure/docs/migrate-loadbalancer.md, controllers/provider-azure/pkg/controller/controlplane/valuesprovider.go, controllers/provider-azure/pkg/controller/controlplane/valuesprovider_test.go
As prerequisite to support Availability Zones on Azure (#135) we need to move to LoadBalancers with the `standard` SKU instead of the `basic` SKU, because only this type of LoadBalancer supports load balancing across zones.
Fixes #207
Update the `ControllerRegistration` for the Azure Provider extension to use a custom build image which contains this PR (dominickistner/gardener-extension-hyper:0.11.0-az-standard-lb).
After the Azure extensions on the Seed cluster are updated, create an Azure Shoot and check after creation has been completed, if the LoadBalancer is of sku `standard`.
To test the upgrade procedure. Create upfront an Azure Shoot with basic LoadBalancer SKU.
Then …
=> Azure: Move to standard loadbalancer

pkg/controller/backupentry/genericactuator/actuator.go
Prevent error logs like
```
{"level":"error","ts":"2019-09-18T02:56:21.822Z","logger":"backupentry_controller","msg":"Error reconciling backupentry","backupentry":"shoot--it--tm-ev3zx--12619378-d916-11e9-ab72-06b1937d9d6b","error":"secrets \"etcd-backup\" is forbidden: unable to create new content in namespace shoot--it--tm-ev3zx because it is being terminated","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/gardener/gardener-extensions/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/gardener/gardener-extensions/pkg/controller/backupentry.(*reconciler).reconcile\n\t/go/src/github.com/gardener/gardener-extensions/pkg/controller/backupentry/reconciler.go:121\ngithub.com/gardener/gardener-extensions/pkg/controller/b …
```
=> BackupEntry generic actuator handles terminating namespaces

go.sum, pkg/controller/controlplane/genericactuator/actuator.go, pkg/controller/controlplane/genericactuator/actuator_test.go, pkg/controller/managedresources.go, pkg/controller/utils.go
We have seen situations in which the shoot namespace in the seed was
hanging in "Terminating" state because the managed resources from the
control plane controller were still existing.
In the [shoot deletion flow](https://github.com/gardener/gardener/blob/master/pkg/controllermanager/controller/shoot/shoot_control_delete.go)
the `ControlPlane` resource is destroyed, and right after that the
kube-apiserver deployment is deleted. If the gardener-resource-manager
is not cleaning up the control plane MRs fast enough then the
kube-apiserver is deleted to fast which will block the
gardener-resource-manager from gracefully cleaning up the MRs.
Thus, now with the waiting mechanism we ensure that the `ControlPlane`
resource is only deleted after the MRs are …
=> Control plane generic actuator waits for managed resources to be deleted

controllers/provider-alicloud/charts/images.yaml, controllers/provider-aws/charts/images.yaml, controllers/provider-azure/charts/images.yaml, controllers/provider-gcp/charts/images.yaml, controllers/provider-openstack/charts/images.yaml, controllers/provider-packet/charts/images.yaml
``` improvement user github.com/gardener/machine-controller-manager #335 @dkistner
MCM supports now Azure machines deployed into availability zones. You can either deploy a machine into a zone or an AvailabilitySet.
```
``` improvement operator github.com/gardener/machine-controller-manager #331 @ialidzhikov
`tzdata` package is now used instead of `assets/zoneinfo.zip` to make all timezones available.
```
``` improvement operator github.com/gardener/machine-controller-manager #331 @ialidzhikov
Base docker image is updated to `alpine:3.10`.
```
``` improvement operator github.com/gardener/machine-controller-manager #330 @prashanth26
On failure to GET machine object, machine creation continues to retry instead of returning failure
```
``` improvement operator …
```
=> [ci:component:github.com/gardener/machine-controller-manager:0.21.1->0.22.0]

controllers/provider-alicloud/charts/images.yaml, controllers/provider-aws/charts/images.yaml, controllers/provider-azure/charts/images.yaml, controllers/provider-gcp/charts/images.yaml, controllers/provider-openstack/charts/images.yaml, controllers/provider-packet/charts/images.yaml
``` improvement operator github.com/gardener/terraformer #24 @ialidzhikov
`tzdata` package is now used instead of `assets/zoneinfo.zip` to make all timezones available.
```
``` noteworthy operator github.com/gardener/terraformer #23 @mvladev
Provider versions are upgraded:
- aws `1.60.0` -> `2.26.0`
- google `1.20.0` -> `2.14.0`
- azurerm `1.22.1` -> `1.33.1`
- openstack `1.16.0` -> `1.21.1`
- alicloud `1.31.0` -> `1.55.2`
- packet `1.7.2` -> `2.3.0`
```
=> [ci:component:github.com/gardener/terraformer:0.13.0->0.14.0]

controllers/provider-alicloud/charts/internal/alicloud-infra/templates/main.tf
This PR is to replace deprecated argument `spec` in alicloud terraform provider with `specification`.
Ref #320
```improvement operator
NONE
```
=> Replace deprecated field in alicloud provider

controllers/provider-azure/charts/internal/azure-infra/templates/main.tf
The bindings of route tables and security groups directly to subnets is deprecated and will be removed in the next major version of the Azurerm terraform provider.
As replacement there are new association resources to bind route tables and security groups to a subnet. Migration will work out of the box.
Fixes partly #320 
```improvement operator
NONE
```
=> Azure: Update deprecated terraform resources

controllers/networking-calico/charts/internal/calico/templates/calico.yaml
Removes the replicase field from the typha deployment to enable the autoscalers to modify it without being reconciled. 
```improvement operator
None
```
=> remove replicase field to enable autoscaling

controllers/provider-alicloud/charts/images.yaml, controllers/provider-aws/charts/images.yaml, controllers/provider-azure/charts/images.yaml, controllers/provider-gcp/charts/images.yaml, controllers/provider-openstack/charts/images.yaml, controllers/provider-packet/charts/images.yaml
``` improvement operator github.com/gardener/terraformer #26 @ialidzhikov
Provider versions are upgraded:
- template `1.0.0` -> `2.1.2`
- null `1.0.0` -> `2.1.2`
```
``` improvement operator github.com/gardener/terraformer #25 @DockToFuture
Added google beta provider
```
=> [ci:component:github.com/gardener/terraformer:0.14.0->0.15.0]

controllers/provider-azure/charts/internal/azure-infra/templates/main.tf, controllers/provider-azure/charts/internal/azure-infra/values.yaml, controllers/provider-azure/pkg/apis/azure/types_infrastructure.go, controllers/provider-azure/pkg/apis/azure/v1alpha1/types_infrastructure.go, controllers/provider-azure/pkg/apis/azure/v1alpha1/zz_generated.conversion.go, controllers/provider-azure/pkg/apis/azure/v1alpha1/zz_generated.deepcopy.go, controllers/provider-azure/pkg/apis/azure/zz_generated.deepcopy.go, controllers/provider-azure/pkg/internal/infrastructure/terraform.go, controllers/provider-azure/pkg/internal/infrastructure/terraform_test.go
Allow to configure Azure service endpoints for Gardener managed subnets.
See the Azure documentation for service endpoints: https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-service-endpoints-overview
If an `Infrastructure` CR reference an invalid service endpoint then Terraform will return an `SubnetHasServiceEndpointWithInvalidServiceName` error code.
See #199
Fixes #199 
```improvement user
The Gardener Azure provider extension support now subnets configured with Azure Service Endpoints.
```
cc @bergerx
=> Azure: Allow to configure service endpoints

controllers/provider-aws/charts/internal/aws-infra/templates/main.tf
Terraform v0.12 does not allow the block syntax (with just braces) when dealing with map arguments (ref https://www.terraform.io/upgrade-guides/0-12.html#attributes-vs-blocks). The PR adapts provider-aws to be terraform v0.12 compatible (without breaking <= v0.12 compatibility).
Fixes #
```improvement operator
NONE
```
=> Prepare provider-aws to terraform v0.12

controllers/networking-calico/charts/internal/calico/templates/calico.yaml
Set calico-typha update strategy to recreate to avoid hanging pods with hostNetwork. 
```improvement operator
None
```
=> fix update strategy for calico-typha deployment

controllers/networking-calico/charts/internal/calico/templates/calico.yaml, controllers/networking-calico/charts/internal/calico/templates/psp/calico-psp.yaml, controllers/networking-calico/charts/internal/calico/templates/psp/calico-typha-horizontal-autoscaler-psp.yaml
Fix calico chart to work when privileged containers are not allowed.
Fixes #341
/cc @vpnachev 
```improvement operator
Allow nodes to join the Shoot when `.spec.kubernetes.allowPrivilegedContainers=false`.
```
=> Fix calico chart to work when privileged containers are not allowed

controllers/provider-alicloud/charts/internal/machine-controller-manager/seed/templates/configmap-monitoring.yaml, controllers/provider-alicloud/charts/internal/seed-controlplane/charts/alicloud-cloud-controller-manager/templates/configmap-monitoring.yaml, controllers/provider-aws/charts/internal/cloud-controller-manager/templates/configmap-monitoring.yaml, controllers/provider-aws/charts/internal/machine-controller-manager/seed/templates/configmap-monitoring.yaml, controllers/provider-azure/charts/internal/cloud-controller-manager/templates/configmap-monitoring.yaml, controllers/provider-azure/charts/internal/machine-controller-manager/seed/templates/configmap-monitoring.yaml, controllers/provider-gcp/charts/internal/cloud-controller-manager/templates/configmap-monitoring.yaml, controllers/provider-gcp/charts/internal/machine-controller-manager/seed/templates/configmap-monitoring.yaml, controllers/provider-openstack/charts/internal/cloud-controller-manager/templates/configmap-monitoring.yaml, controllers/provider-openstack/charts/internal/machine-controller-manager/seed/templates/configmap-monitoring.yaml, controllers/provider-packet/charts/internal/machine-controller-manager/seed/templates/configmap-monitoring.yaml, controllers/provider-packet/charts/internal/seed-controlplane/charts/packet-cloud-controller-manager/templates/configmap-monitoring.yaml
Change monitoring ConfigMaps' syntax of provider-specific components to be easily integrated with Gardener's Prometheus' configurations and Grafana's dashboards.
Fixes #https://github.com/gardener/gardener/issues/1351
```improvement operator
Change monitoring ConfigMaps' syntax of provider-specific components
```
=> Change monitoring ConfigMaps' syntax of provider-specific components

controllers/provider-openstack/charts/images.yaml
Added support for the 1.16 version of CCM for OpenStack. The 1.16 CCM version should be also used for the 1.15 clusters as it fixes a few LoadBalancer related issues (https://github.com/kubernetes/cloud-provider-openstack/pull/742) and introduces additional authentication fields (https://github.com/kubernetes/cloud-provider-openstack/pull/735 & https://github.com/kubernetes/cloud-provider-openstack/pull/733).
Part of #154
```improvement operator
Added support for the 1.16 version CCM for OpenStack
```
=> Added support for OpenStack CCM 1.16

controllers/provider-alicloud/pkg/webhook/controlplanebackup/ensurer_test.go, controllers/provider-aws/pkg/webhook/controlplanebackup/ensurer_test.go, controllers/provider-azure/pkg/webhook/controlplanebackup/ensurer_test.go, controllers/provider-gcp/pkg/webhook/controlplanebackup/ensurer_test.go, controllers/provider-openstack/pkg/webhook/controlplanebackup/ensurer_test.go, controllers/provider-packet/pkg/webhook/controlplanebackup/ensurer_test.go, pkg/webhook/controlplane/etcd.go
This PR fixes https://github.com/gardener/gardener-extensions/pull/337#issuecomment-537857510. And use shootUID for randomiaztion of schedule
Fixes #
```improvement operator
NONE
```
=> Use shootUID for randomization of backup schedule

controllers/provider-alicloud/pkg/controller/controlplane/valuesprovider.go, controllers/provider-aws/pkg/controller/controlplane/valuesprovider.go, controllers/provider-azure/pkg/controller/controlplane/valuesprovider.go, controllers/provider-gcp/pkg/controller/controlplane/valuesprovider.go, controllers/provider-openstack/pkg/controller/controlplane/valuesprovider.go, controllers/provider-packet/pkg/controller/controlplane/valuesprovider.go
Adding null checks for valueproviders. Currently valueproviders assume that provider configs in ControlPlane is always set. It is an optional field and thus cannot be assumed.
Fixes #
```improvement operator
```
=> adding null checks for valueproviders

controllers/provider-azure/charts/internal/cloud-provider-config/templates/cloud-provider-config.tpl, controllers/provider-azure/charts/internal/cloud-provider-config/values.yaml, controllers/provider-azure/pkg/controller/controlplane/valuesprovider.go, controllers/provider-azure/pkg/controller/controlplane/valuesprovider_test.go
We will use again basic load balancers for cluster with availability sets and standard only for zoned clusters.
Fixes #359
```improvement user
Azure: Shoot clusters with AvailabilitySets need to use again basic sku load balancers due to routing/nat issues of this combination. Zoned clusters will still use the standard sku load balancers.
```
```action operator
Azure: Shoot clusters with AvailabilitySet and standard sku load balancers need to migrated to use basic sku load balancers again, due to routing/nat issues of this combination. This works as the migration from basic to standard. See here: https://github.com/gardener/gardener-extensions/blob/master/controllers/provider-azure/docs/migrate-loadbalancer.md
```
=> Fix: Azure lb issue in combination with avSet

controllers/networking-calico/charts/internal/calico/templates/config.yaml
Enable bandwidth plugin on for CNI config**Which issue(s) this PR fixes**:
Fixes #358 
```improvement developer
It is now possible to shape pod traffic by using the  `kubernetes.io/ingress-bandwidth` and `kubernetes.io/egress-bandwidth` annotations. This is possible only for Calico versions >= 3.8. For lower versions of calico the annotations will have a no-op. 
```
=> Switch on the bandwidth plugin for CNI config

controllers/provider-alicloud/charts/images.yaml, controllers/provider-aws/charts/images.yaml, controllers/provider-azure/charts/images.yaml, controllers/provider-gcp/charts/images.yaml, controllers/provider-openstack/charts/images.yaml, controllers/provider-packet/charts/images.yaml
``` noteworthy operator github.com/gardener/terraformer #27 @ialidzhikov
Terraform version has been upgraded to `0.12.9`.
```
=> [ci:component:github.com/gardener/terraformer:0.15.0->0.16.0]

controllers/networking-calico/charts/internal/calico/templates/calico.yaml
Configure Calico to correctly use Host-local IPAM. 
In addition to the IPAM config, the `CALICO_IPV4POOL_IPIP` was set to `Never` instead of `Always` to avoid side-effects since anyways tunnels are not used for Azure (backends are set to none). 
```action operator
Its recommended to modify the `IPPool` resource in Azure shoots by setting the `spec.ipipMode` mode to `Never`. This is to ensure consistent configuration and to avoid side effects in the future. 
```
=> Enable Using POD CIDRs on calico node/typha

.test-defs/provider-alicloud.yaml, .test-defs/provider-aws.yaml, .test-defs/provider-azure.yaml, .test-defs/provider-gcp.yaml, .test-defs/provider-openstack.yaml, controllers/provider-alicloud/test/tm/generator.go, controllers/provider-aws/test/tm/generator.go, controllers/provider-azure/test/tm/generator.go, controllers/provider-gcp/test/tm/generator.go, controllers/provider-openstack/test/tm/generator.go, go.mod, test/tm/generator/helper.go
This PR adds the generation of provider specific configuration that is then written as yaml to a specified path.
These configurations are intended to be used by `create shoot` in https://github.com/gardener/gardener/pull/1474 .
For now only the necessary provider specific configuration is implemented to get the same functionality as before the extension story.
Therefore, not all configuration is exposed (like CIDR's) and OS and network configurations are implemented as we need special configuration for tests.
Currently the kind of a configuration is received with `reflect.TypeOf(v1alpha1.InfrastructureConfig{}).Name()` as it is implemented by the apimachinery runtime in `AddKnownTypes`.
Is there are better of …
=> Add provider config generation for create shoot tests

controllers/extension-shoot-cert-service/charts/images.yaml
``` improvement operator github.com/gardener/cert-management $51247dd5f8631382ba69a878cdf4b25155c3cf02
restrict watching issuer and secrets on default cluster to issuer namespace
```
``` improvement operator github.com/gardener/cert-management $51247dd5f8631382ba69a878cdf4b25155c3cf02
metrics on ACME obtains and DNS challenges
```
``` improvement operator github.com/gardener/cert-management $51247dd5f8631382ba69a878cdf4b25155c3cf02
email is not stored in issuer secret anymore
```
=> [ci:component:github.com/gardener/cert-management:0.2.2->0.2.3]

controllers/extension-shoot-dns-service/charts/images.yaml
``` improvement operator github.com/gardener/external-dns-management #42 @MartinWeindel
dealing with owner conflict caused by stale cache from external changes, e.g. for DNSEntries moved between two dns-controller-managers working on the same hosted zone.
```
``` improvement operator github.com/gardener/external-dns-management #38 @afritzler
Added addional OpenStack credential flags (domainID, tenantID, userDomainName, userDomainID)
```
``` improvement operator github.com/gardener/external-dns-management $634b5af8a253db05dd553466afb97c6defb7b49e
Added additional OpenStack credential flags. It now support the following properties:
userDomanName, OS_USER_DOMAIN_NAME
userDomainID, OS_USER_DOMAIN_ID
tenantID, OS_PROJECT_ID
domainID, OS_DOMAIN_ID
```
=> [ci:component:github.com/gardener/external-dns-management:0.7.0->0.7.1]

controllers/provider-alicloud/charts/internal/machine-controller-manager/seed/templates/clusterrole.yaml, controllers/provider-alicloud/example/20-crd-managedresource.yaml, controllers/provider-alicloud/example/20-crd-operatingsystemconfig.yaml, controllers/provider-alicloud/example/20-crd-vpa.yaml, controllers/provider-aws/charts/internal/machine-controller-manager/seed/templates/clusterrole.yaml, controllers/provider-aws/example/20-crd-managedresource.yaml, controllers/provider-aws/example/20-crd-operatingsystemconfig.yaml, controllers/provider-aws/example/20-crd-vpa.yaml, controllers/provider-azure/charts/internal/machine-controller-manager/seed/templates/clusterrole.yaml, controllers/provider-azure/example/20-crd-managedresource.yaml, controllers/provider-azure/example/20-crd-operatingsystemconfig.yaml, controllers/provider-azure/example/20-crd-vpa.yaml, controllers/provider-gcp/charts/internal/machine-controller-manager/seed/templates/clusterrole.yaml, controllers/provider-gcp/example/20-crd-managedresource.yaml, controllers/provider-gcp/example/20-crd-operatingsystemconfig.yaml, controllers/provider-gcp/example/20-crd-vpa.yaml, controllers/provider-openstack/charts/internal/machine-controller-manager/seed/templates/clusterrole.yaml, controllers/provider-openstack/example/20-crd-managedresource.yaml, controllers/provider-openstack/example/20-crd-operatingsystemconfig.yaml, controllers/provider-openstack/example/20-crd-vpa.yaml, controllers/provider-packet/charts/internal/machine-controller-manager/seed/templates/clusterrole.yaml, controllers/provider-packet/example/20-crd-managedresource.yaml, controllers/provider-packet/example/20-crd-operatingsystemconfig.yaml, controllers/provider-packet/example/20-crd-vpa.yaml, go.sum
Today, the created cluster roles for MCM never get cleaned up. With this owner reference we ensure that, as soon as the shoot namespace in the seed is deleted, the garbage collector also deletes this cluster role.
Along the way I added a few missing example CRDs to the provider extensions example directories.
```improvement operator
The `Worker` controller of all provider extensions does now properly ensure clean-up of its created `ClusterRole`s for the machine-controller-manager after shoot deletion.
```
=> Add missing owner reference to MCM cluster role

controllers/provider-alicloud/charts/images.yaml, controllers/provider-aws/charts/images.yaml, controllers/provider-azure/charts/images.yaml, controllers/provider-gcp/charts/images.yaml, controllers/provider-openstack/charts/images.yaml, controllers/provider-packet/charts/images.yaml
``` improvement user github.com/gardener/machine-controller-manager #344 @dkistner
Create and manage Azure virtual machines assigned to a virtual network (vNet), which is located in a different resource group than the machines.
```
``` improvement developer github.com/gardener/machine-controller-manager #343 @afritzler
Added multi stage docker build
```
``` improvement operator github.com/gardener/machine-controller-manager #342 @prashanth26
Updated Integration Tests kubectl to `v1.16.0`
```
``` improvement operator github.com/gardener/machine-controller-manager #341 @prashanth26
Fixes leaks in Go Routines leading to CPU wastage
```
``` noteworthy operator github.com/gardener/machine-controller-manager #340 @prashanth26
⚠️ GCP VM's Public IP attachment is now optional. …
```
=> [ci:component:github.com/gardener/machine-controller-manager:0.22.0->0.23.0]

controllers/provider-azure/charts/internal/cloud-controller-manager/templates/cloud-controller-manager.yaml
Set concurrent-service-syncs to 1 for Azure Cloud Controller Managers to avoid parallel operations on the Shoot LoadBalancer on Azure which cause inconsistencies in the LoadBalancer configuration.
This is a workaround (probably also the fix) for https://github.com/kubernetes/kubernetes/issues/84052
```improvement operator
An issue with parallel LoadBalancer updates on Azure which caused inconsistencies in the LoadBalancer configuration is now fixed by disabling concurrent LoadBalancer operation executed by the Azure Cloud Controller Manager. Latest k8s version can be consumed again.
```
=> Azure: Avoid parallel LoadBalancer operations

controllers/provider-alicloud/charts/internal/machine-controller-manager/seed/templates/deployment.yaml, controllers/provider-aws/charts/internal/machine-controller-manager/seed/templates/deployment.yaml, controllers/provider-azure/charts/internal/machine-controller-manager/seed/templates/deployment.yaml, controllers/provider-gcp/charts/internal/machine-controller-manager/seed/templates/deployment.yaml, controllers/provider-openstack/charts/internal/machine-controller-manager/seed/templates/deployment.yaml, controllers/provider-packet/charts/internal/machine-controller-manager/seed/templates/deployment.yaml
Reduce limits for control plane components for which VPA is deployed. The `limits` are now controlled by VPA in its version 0.6+
Fixes #
```improvement operator
```
=> Reduce limits for control plane components for which VPA is deployed

go.mod, go.sum, vendor/modules.txt
The dependency Gardener in version `c27ebd04a82b` has an invalid dependency `github.com/gardener/external-dns-management v0.0.0-20190220100540-eb4bbb5832a03` (not existing commit hash -> `b4bbb5832a03`).
@ialidzhikov fixed this it in Gardener with commit `82369df93f78` (https://github.com/gardener/gardener/commit/82369df93f78e7b585efe98911a73b80046038a6). We need to use this commit or higher to use the extension repo as dependency in Gardener.
Vendoring the `gardener-extension` in Gardener failed with this issue:
```
go: github.com/gardener/gardener-extensions@v0.0.0-20191028054109-f37a873929da requires
github.com/gardener/gardener@v0.0.0-20191025063857-c27ebd04a82b requires
github.com/gardener/external-dns-management@v0.0.0-20190220100540-eb4bbb5832a03: invalid version: unknown revision …
```
=> Bump Gardener version to fix vendor issues

.ci/component_descriptor
We now can handle the same container image with the same name and different version, so this workaround is
not neede anymore.
This reverts commit b6e58bd577608459c8b3a812a788687f524e6a8c.
Fixes #
```improvement operator
```
=> Revert "include controller dirname in logical image name"

controllers/provider-gcp/charts/internal/machineclass/templates/machineclass.yaml, controllers/provider-gcp/charts/internal/machineclass/values.yaml, controllers/provider-gcp/pkg/controller/worker/machines.go, controllers/provider-gcp/pkg/controller/worker/machines_test.go
Fix machine class generate for disabling public IPs. 
```improvement user
An issue that prevented GCP shoot worker nodes from getting external IP addresses has been fixed.
```
=> Fix machineclass generation for cloudnat

controllers/provider-aws/pkg/controller/controlplane/valuesprovider.go
Fix an invalid check in the control plane values provider for AWS.
```improvement user
An issue that prevented the control plane deployment for AWS shoots that don't specify a `controlPlaneConfig` in the `Shoot` specification has been resolved.
```
=> Fix invalid check in control plane values provider for AWS

controllers/provider-openstack/charts/internal/shoot-storageclasses/templates/storageclasses.yaml
All default storage classes have the `default` name, but OpenStack storage class has the `default-class`. This breaks multi-cluster compatibility.
@rfranzke suggested to keep an old `default-class` for a while, therefore we keep it as non-default.
```improvement operator
OpenStack: rename the default storage class from "default-class" to "default"
```
=> OpenStack: set the "default" name for a default storage class

controllers/provider-azure/charts/internal/machineclass/templates/machineclass.yaml, controllers/provider-azure/charts/internal/machineclass/values.yaml, controllers/provider-azure/docs/usage-as-end-user.md, controllers/provider-azure/docs/usage-as-operator.md, controllers/provider-azure/pkg/controller/worker/machines.go, controllers/provider-azure/pkg/controller/worker/machines_test.go
Currently the Azure provider extension does not pass the configured os volume type to the `AzureMachineClass` and the machine-controller-manager will in consequence create machines always with the default os disk belonging to the requested machine type.
This will now change. The Azure provider will write the volume type now to the `AzureMachineClass`, but only if the passed volume type is a valid Azure volume type. Otherwise the default volume type of the machine type will be used.
```improvement user
The os volume type configuration for worker machines of Azure Shoot cluster will be now passed correctly, but only if the selected volume type is a valid Azure volume type.
This will trigger a rolling update of all machines in the …
```
=> Azure: Enable os disk configuration

controllers/os-suse-jeos/pkg/generator/templates/cloud-init-suse-jeos.template, controllers/os-suse-jeos/pkg/generator/testfiles/cloud-init
The PR adds the code, which ensures that required packages are installed in SUSE OS.
Fixes #399
I put the package installation into the loop, because zypper lock file can be in place during the boot. Default cloud-init `packages:` can fail because of this and packages can be missing during the boot.
7 return code means that the zypper is locked: [ZYPPER_EXIT_ZYPP_LOCKED](https://en.opensuse.org/SDB:Zypper_manual_(plain))
Even if the `zypper install` fails, the further commands in the `runcmd:` list will be executed. If the packages are already installed and there are no repos configured, zypper will just return 0.
```improvement operator
Ensure required packages …
```
=> JeOS: ensure required packages are installed

controllers/os-suse-jeos/pkg/generator/generator.go, controllers/os-suse-jeos/pkg/generator/invalid_config_test.go
With the recently merged #297 env vars were introduced to allow configuration of the SuSE-JeOS controller. It turns out that these env vars are indirectly required by all extensions when the hyper binary is used. Now if these env vars are unset, default values will be used instead to fail.
Fixes #
```improvement operator
Make the env vars `OS_CONFIG_FORMAT` and `BOOT_COMMAND` optional to allow the hyper binary to run without them.
```
=> Use defaults for env vars

pkg/terraformer/terraformer.go
Restrict terraformer to delete jobs and pods only in its namespace.
Fixes #424 
```improvement operator
terraformer does now delete job and pods only in its namespace. This fixes an issue that prevents simultaneous creation of Shoots with the same name (but different projects) on the same Seed.
```
=> Restrict terraformer to delete jobs and pods only in its namespace

controllers/provider-alicloud/charts/internal/machine-controller-manager/shoot/templates/role-machine-controller-manager.yaml, controllers/provider-alicloud/charts/internal/machine-controller-manager/shoot/templates/rolebinding-machine-controller-manager.yaml, controllers/provider-aws/charts/internal/machine-controller-manager/shoot/templates/role-machine-controller-manager.yaml, controllers/provider-aws/charts/internal/machine-controller-manager/shoot/templates/rolebinding-machine-controller-manager.yaml, controllers/provider-azure/charts/internal/machine-controller-manager/shoot/templates/role-machine-controller-manager.yaml, controllers/provider-azure/charts/internal/machine-controller-manager/shoot/templates/rolebinding-machine-controller-manager.yaml, controllers/provider-gcp/charts/internal/machine-controller-manager/shoot/templates/role-machine-controller-manager.yaml, controllers/provider-gcp/charts/internal/machine-controller-manager/shoot/templates/rolebinding-machine-controller-manager.yaml, controllers/provider-openstack/charts/internal/machine-controller-manager/shoot/templates/role-machine-controller-manager.yaml, controllers/provider-openstack/charts/internal/machine-controller-manager/shoot/templates/rolebinding-machine-controller-manager.yaml, controllers/provider-packet/charts/internal/machine-controller-manager/shoot/templates/role-machine-controller-manager.yaml, controllers/provider-packet/charts/internal/machine-controller-manager/shoot/templates/rolebinding-machine-controller-manager.yaml
This is prerequisite for solving issue #[179](https://github.com/gardener/machine-controller-manager/issues/179)
With this PR MCM will have permissions to create bootsrap token in the shoot cluster
Part of [#179](https://github.com/gardener/machine-controller-manager/issues/179)
```improvement operator
MCM has new role for create, delete and list secrets in shoot's kube-system namespace
```
=> add role to allow bootstrap token creation in the kube-system namespce of the shoot by MCM

controllers/extension-shoot-dns-service/charts/images.yaml
dns-controller-manager version 0.7.2 fixes the issue that the name of image in component descriptor. Now the image name is the same as what is used by *extension-shoot-dns-service*. 
Fixes #
``` improvement user github.com/gardener/external-dns-management #43 @mandelsoft
For openstack designate it is possible now to 
specify a CA certificate in the credentails. The key is CACERT.
Additionally a dedicated client certificate and key can used
for the https requests (CLIENTCERT/CLIENTKEY)
```
=> Set dns-controller-manager version to 0.7.2

controllers/extension-shoot-cert-service/charts/images.yaml
``` improvement operator github.com/gardener/cert-management $5fa6f75bde5b7747e30fcdd12206bda85d6fc779
helm charts: splitting value `createCRDs` into two separate values
`createCRDs.issuers` and `createCRDs.certificates`
```
=> [ci:component:github.com/gardener/cert-management:0.2.5->0.2.6]

controllers/provider-alicloud/pkg/controller/common/terraform.go, controllers/provider-alicloud/pkg/controller/common/terraform_test.go, controllers/provider-alicloud/pkg/controller/infrastructure/actuator_test.go, controllers/provider-aws/pkg/controller/infrastructure/actuator.go, controllers/provider-azure/pkg/internal/terraform.go, controllers/provider-gcp/pkg/internal/terraform.go, controllers/provider-openstack/pkg/internal/terraform.go, controllers/provider-packet/pkg/controller/infrastructure/actuator.go, pkg/mock/gardener-extensions/terraformer/mocks.go, pkg/terraformer/config.go, pkg/terraformer/state.go, pkg/terraformer/terraform_test.go, pkg/terraformer/terraformer.go, pkg/terraformer/types.go, pkg/terraformer/waiter.go
Currently we use Job for terraform apply/destroy operations. The Job controller starts a  new Pod if the first Pod fails or is deleted. When the first `tf-job` Pod is deleted, it is being gracefully terminated for given period of `activeDeadlineSeconds` (630 in our case). However the Job controller start a new `tf-job` Pod which at the end of its execution overrides the correct terraform state of the first `tf-job` Pod.
This PR adapts the terraformer package (`pkg/terraformer`) to use Pod to prevent multiple Pods executing simultaneously terraform apply/destroy.
Fixes #182
Fixes #202
Fixes #428
```improvement operator
`pkg/terraformer` package does now use a Pod …
```
=> Switch from job to pod for terraform apply/destroy

pkg/controller/controlplane/genericactuator/actuator.go, pkg/controller/controlplane/genericactuator/actuator_test.go, pkg/controller/managedresources.go, pkg/controller/worker/genericactuator/machine_controller_manager.go
Co-Authored-by: Tim Ebert <tim.ebert@sap.com>
Previously the storage class name was `default`, however, this PR https://github.com/gardener/gardener-extensions/pull/415 caused two default storage classes to co-exist at the same time. To avoid this, we now use the `forceOverwriteAnnotations` flag from the `gardener-resource-manager` to ensure that all the annotations are updated accordingly.  
Fixes #
This is done for all storage-class charts. 
```improvement developer
The default storage class annotations are now overwritten to the desired values using the `forceOverwriteAnnotation` parameter in the `extension-controlplane-storageclasses` managed resource. 
```
=> Fix defaulting for storage classes

controllers/provider-alicloud/charts/images.yaml, controllers/provider-aws/charts/images.yaml, controllers/provider-azure/charts/images.yaml, controllers/provider-gcp/charts/images.yaml, controllers/provider-openstack/charts/images.yaml, controllers/provider-packet/charts/images.yaml
``` action user github.com/gardener/machine-controller-manager #353 @vpnachev
Since version `0.22.0` the fields `Spec.Properties.StorageProfile.ImageReference.[Publisher|Offer|Sku|Version]` in the `AzureMachineClass have been deprecated and now they are completely removed. Please switch to `Spec.Properties.StorageProfile.ImageReference.URN` before upgrading to this version or higher.
```
``` improvement operator github.com/gardener/machine-controller-manager #348 @hardikdr
Node-conditions are configurable via flag. Users can provide the list of node-conditions based on which machines are replaced if set to true for health-timeout period.
```
``` improvement operator github.com/gardener/machine-controller-manager #347 @prashanth26
Deletes any Azure infra resources before …
```
=> [ci:component:github.com/gardener/machine-controller-manager:0.23.0->0.24.0]

controllers/extension-shoot-cert-service/charts/images.yaml
``` improvement operator github.com/gardener/cert-management #7 @MartinWeindel
fix for "Panic if ingress spec.tls.hosts not specified" (issue #6)
```
``` improvement operator github.com/gardener/cert-management $80a07c00937a3ac7a53af07fa0e8a4203678c28f
fix for "Panic if ingress spec.tls.hosts not specified" (issue #6)
```
=> [ci:component:github.com/gardener/cert-management:0.2.6->0.2.7]

controllers/extension-shoot-cert-service/charts/images.yaml
``` improvement operator github.com/gardener/cert-management #9 @MartinWeindel
Existing certificate secrets with type `kubernetes.io/tls` can be updated
to simplify migration from cert-broker/cert-manager.
```
=> [ci:component:github.com/gardener/cert-management:0.2.7->0.2.8]

controllers/provider-alicloud/charts/images.yaml
Fix issue CVE-2019-11255: CSI volume snapshot, cloning and resizing features can result in unauthorized volume data access or mutation.
This issue only occurs in AliCloud for k8s v1.13.
https://github.com/kubernetes/kubernetes/issues/85233#.
```improvement user
Issue CVE-2019-11255 is fixed, which only affected shoot clusters in k8s version 1.13.
```
=> Fix  CSI volume security issue on AliCloud for k8s v1.13

controllers/provider-alicloud/charts/images.yaml
Fix issue CVE-2019-11255: CSI volume snapshot, cloning and resizing features can result in unauthorized volume data access or mutation.
This issue only occurs in AliCloud for k8s v1.13.
https://github.com/kubernetes/kubernetes/issues/85233#.
```improvement user
Issue CVE-2019-11255 is fixed, which only affected shoot clusters in k8s version 1.13.
```
=> Fix CSI volume security issue on AliCloud for k8s v1.13

controllers/networking-calico/charts/internal/calico/templates/typha-vertical-autoscaling-config.yaml
According to `kubernetes-incubator/cluster-proportional-vertical-autoscaler` the config name in the ConfigMap (`calico-typha-deploy`) should match the container name (`calico-typha`)in the target resource.
Fixes #454
```improvement operator
An issue preventing `calico-typha-vertical-autoscaler` to patch (scale) `calico-typha-deploy` is now fixed.
```
=> Fix typha calico-typha-vertical-autoscaler

controllers/provider-alicloud/pkg/controller/controlplane/valuesprovider.go, controllers/provider-alicloud/pkg/controller/controlplane/valuesprovider_test.go, controllers/provider-packet/pkg/controller/controlplane/valuesprovider.go, controllers/provider-packet/pkg/controller/controlplane/valuesprovider_test.go, pkg/controller/controlplane/genericactuator/actuator.go, pkg/controller/controlplane/genericactuator/actuator_test.go, pkg/controller/controlplane/genericactuator/noopvaluesprovider.go, pkg/mock/gardener-extensions/controller/controlplane/genericactuator/mocks.go
Co-authored-by: Uwe Krueger <uwe.krueger@sap.com>
Add checksum to shoot control plane chart values interface. Those checksum might be needed for in-cluster object which have to be restarted when their corresponding secret object changes (e.g. `csi-node-plugin`).
```improvement developer
```
=> Introduced checksums for shoot controlplane chart values

controllers/provider-alicloud/pkg/alicloud/client/client.go, controllers/provider-aws/pkg/aws/client/client.go
Add bucket lifecycle rule for AWS and Alicloud to cleanup incomplete multipart uploads after expiration period.
Fixes #
Please do-not-merge until i confirm anything is missing. The code wise and documentation wise PR is ready. But to test that, its actually taking effect, i have created a bucket with partial multipart uploads for both OSS and AWS account. The lifecycle configuration is set using controller. But i will check post two days if configuration  does clear these incomplete parts.
```improvement operator
Add bucket lifecycle rule on AWS S3 and OSS bucket to cleanup incomplete multipart uploads …
```
=> Add bucket lifecycle rule for incomplete multipart uploads

controllers/extension-shoot-cert-service/charts/images.yaml
``` improvement operator github.com/gardener/cert-management #10 @MartinWeindel
The release tags from now are prefixed with `v`.
```
=> [ci:component:github.com/gardener/cert-management:0.2.8->v0.2.9]

controllers/provider-alicloud/pkg/controller/worker/machines.go, controllers/provider-alicloud/pkg/controller/worker/machines_test.go, controllers/provider-aws/pkg/controller/worker/machines.go, controllers/provider-aws/pkg/controller/worker/machines_test.go, controllers/provider-azure/pkg/controller/worker/machines.go, controllers/provider-azure/pkg/controller/worker/machines_test.go, controllers/provider-gcp/pkg/controller/worker/machines.go, controllers/provider-gcp/pkg/controller/worker/machines_test.go, controllers/provider-openstack/pkg/controller/worker/machines.go, controllers/provider-openstack/pkg/controller/worker/machines_test.go, controllers/provider-packet/pkg/controller/worker/machines.go, controllers/provider-packet/pkg/controller/worker/machines_test.go, go.sum, pkg/controller/worker/machines.go, pkg/controller/worker/machines_test.go
In order to prevent undesired rolling updates the hash value for machine resources is now computed only out of 
* machine type
* volume type + size
* worker pool provider config
* kubernetes version
* machine image name + version
/cc @vlerenc 
```noteworthy user
:warning: In order to prevent undesired rolling updates of machine resources the hash value computation has changed. A rolling update of worker nodes is now only happening if one of the following properties is changed: Kubernetes major/minor version, machine image name or version, machine type, volume type or size, worker pool provider configuration. Deploying this change will, one last time, roll out all nodes of all clusters.
```
=> Change computation of hash value for machine resources

controllers/provider-aws/charts/internal/aws-infra/templates/main.tf
This PR removes all ingress and egress rules from the default AWS VPC security group in case it is managed by Gardener.
/cc @vlerenc @ThormaehlenFred 
```noteworthy user
The AWS infrastructure controller does now remove all ingress and egress rules from the default VPC security group in case it is managed by Gardener. It doesn't touch the default VPC security group in case a shoot uses an already existing VPC.
```
=> Remove all rules from default AWS VPC security group

controllers/extension-shoot-cert-service/charts/images.yaml
Prior to v0.2.9 of cert-management, the image name generated in component_descriptor is controller-manager, while in extension-shoot-cert-service/charts/images.yml, the name is cert-management. This is causing cc-utils to be unable to read image information from component_descriptor using the images.yml extension-shoot-cert-service provide.
From v0.2.9, the image name in component_descriptor of cert-management is changed to cert-management so that it can be read by cc-utils.
Fixes #
``` improvement operator github.com/gardener/cert-management #12 @MartinWeindel
improved behaviour if same certificate is requested multiple times simultaneously
```
``` improvement …
```
=> [release-1.0] Upgrade shoot-cert-service image version to v0.2.10

controllers/provider-alicloud/charts/images.yaml, controllers/provider-aws/charts/images.yaml, controllers/provider-azure/charts/images.yaml, controllers/provider-gcp/charts/images.yaml, controllers/provider-openstack/charts/images.yaml, controllers/provider-packet/charts/images.yaml
``` improvement operator github.com/gardener/machine-controller-manager #366 @jia-jerry
AliCloud: When nodes are rolling updated, pods with Persistent volume attached can now be evicted correctly/serially before the node is drained.
```
``` improvement operator github.com/gardener/machine-controller-manager #365 @prashanth26
Bugfix: Remove dependency on MachineClass while deleting MachineDeployment/MachineSets
```
``` improvement operator github.com/gardener/machine-controller-manager #364 @prashanth26
Bugfix: Allow deletion of machine without status.currentStatus.phase
```
``` improvement operator github.com/gardener/machine-controller-manager #362 @ialidzhikov
The release tags from now are prefixed with `v`.
```
``` improvement developer …
```
=> [ci:component:github.com/gardener/machine-controller-manager:0.24.0->v0.25.0]

controllers/extension-shoot-dns-service/charts/images.yaml
``` improvement operator github.com/gardener/external-dns-management #47 @ialidzhikov
The release tags from now are prefixed with `v`.
```
```improvement operator github.com/gardener/external-dns-management #50 @MartinWeindel 
aws-route53: avoid temporary deletion of DNS records after restart with unavailable or throttled route53 API
```
=> Update dns-controller-manager to v0.7.3

controllers/networking-calico/docs/usage-as-end-user.md, controllers/os-suse-jeos/pkg/generator/templates/cloud-init/suse-jeos.template, controllers/os-suse-jeos/pkg/generator/templates/script/suse-jeos.template, controllers/os-suse-jeos/pkg/generator/testfiles/cloud-init/cloud-init, controllers/os-suse-jeos/pkg/generator/testfiles/script/cloud-init
Use MTU of 1460 for all SUSE nodes
Fixes #497 
Thanks to @marwinski  and @zanetworker .
```improvement operator
SuSE nodes are now using mtu of 1460 on all infrastructures.
```
```improvement user
An issue where calico typha was not working with SuSE nodes has been fixed. Now SuSE based cluster can enable calico typha again and benefit from it.
```
=> Use MTU of 1460 for all SUSE nodes

controllers/provider-alicloud/pkg/controller/infrastructure/actuator.go, controllers/provider-alicloud/pkg/controller/infrastructure/actuator_test.go, controllers/provider-aws/pkg/controller/infrastructure/actuator_reconcile.go, controllers/provider-azure/pkg/controller/infrastructure/actuator.go, controllers/provider-azure/pkg/controller/infrastructure/actuator_reconcile.go, controllers/provider-gcp/pkg/controller/infrastructure/actuator.go, controllers/provider-gcp/pkg/controller/infrastructure/actuator_reconcile.go, controllers/provider-openstack/pkg/controller/infrastructure/actuator.go, controllers/provider-openstack/pkg/controller/infrastructure/actuator_reconcile.go, controllers/provider-packet/pkg/controller/infrastructure/actuator_reconcile.go, pkg/mock/gardener-extensions/terraformer/mocks.go, pkg/terraformer/config.go, pkg/terraformer/raw_state.go, pkg/terraformer/terraform_test.go, pkg/terraformer/terraformer.go, pkg/terraformer/types.go
With this PR we copy the terraformer state from the configmap <shoot-name>.infra.tf-state into the Infrastructure's Status under State as runtime.RawExtension. The State is base64 encoded to make the infra resource small as posible. 
Part of [#1631](https://github.com/gardener/gardener/issues/1631)
```improvement operator
All `Infrastructure` extension controllers do now copy the Terraformer state into the `Infrastructure`'s `.status.state` field.
```
=> Put Infrastructure state into status as runtime.RawExtension

controllers/networking-calico/docs/usage-as-end-user.md, controllers/os-suse-jeos/pkg/generator/templates/cloud-init/suse-jeos.template, controllers/os-suse-jeos/pkg/generator/templates/script/suse-jeos.template, controllers/os-suse-jeos/pkg/generator/testfiles/cloud-init/cloud-init, controllers/os-suse-jeos/pkg/generator/testfiles/script/cloud-init
Cherry pick #500 
Fixes #
```improvement operator
SuSE nodes are now using mtu of 1460 on all infrastructures.
```
```improvement user
An issue where calico typha was not working with SuSE nodes has been fixed. Now SuSE based cluster can enable calico typha again and benefit from it.
```
=> [rel-v1.0] Use MTU of 1460 for all SUSE nodes

controllers/provider-openstack/charts/images.yaml
Bumped OpenStack CCM to v1.17.0
```improvement operator
Added support for OpenStack CCM v1.17.0
```
=> Bumped OpenStack CCM to v1.17.0

controllers/networking-calico/charts/internal/calico/templates/node/configmap-calico-config.yaml, controllers/networking-calico/charts/internal/calico/templates/node/daemonset-calico-node.yaml, controllers/networking-calico/charts/internal/calico/values.yaml, controllers/networking-calico/docs/usage-as-end-user.md, controllers/networking-calico/hack/api-reference/calico.md, controllers/networking-calico/pkg/apis/calico/types_network.go, controllers/networking-calico/pkg/apis/calico/v1alpha1/types_network.go, controllers/networking-calico/pkg/apis/calico/v1alpha1/zz_generated.conversion.go, controllers/networking-calico/pkg/apis/calico/v1alpha1/zz_generated.deepcopy.go, controllers/networking-calico/pkg/apis/calico/zz_generated.deepcopy.go, controllers/networking-calico/pkg/charts/charts_test.go, controllers/networking-calico/pkg/charts/utils.go
let user configure the mtu for shoot worker node
Fixes #
NONE
```noteworthy user
If you wish to configure the MTU value of calico then you can set the `.spec.vethMTU` field in the `calico.networking.extensions.gardener.cloud/v1alpha1.NetworkConfig`. Please make sure that all the MTUs in your environment, failure to do so will result in performance penalties and packet loss.
```
=> feat: configure shoot worker node calico port mtu

controllers/extension-shoot-cert-service/pkg/controller/actuator.go
If a shoot does not not have a DNS domain (which is possible as of gardener/gardener#1617) then the certificate-service extension does not do anything.
/assign @timuthy 
```improvement operator
NONE
```
=> Certificate extension copes with no DNS shoots

controllers/networking-calico/README.md
Adds documentation to the `networking-calico` extensions.
```improvement developer
Documentation for the networking-calico extensions has been added.
```
=> Add documentation for the networking-calico extension

controllers/provider-azure/charts/internal/cloud-controller-manager-shoot/templates/rbac-cloud-controller.yaml
Allow Azure cloud-controller to create Service events.
Azure Services can now have Events also from source `azure-cloud-provider` (in addition to the existing source `service-controller`).
For example:
```
$ k describe svc -n kube-system vpn-shoot
Events:
Type     Reason                    Age                  From                  Message
----     ------                    ----                 ----                  -------
Normal   EnsuringLoadBalancer      53m (x5 over 54m)    service-controller    Ensuring load balancer
Warning  SyncLoadBalancerFailed    53m (x5 over 54m)    service-controller    Error syncing load balancer: failed to ensure load balancer: autorest/azure: Service returned an error. Status=<nil> Code="ScopeLocked" Message="The …
```
=> Allow Azure cloud-controller to create service events

hack/check.sh, hack/install-requirements.sh
Revert golangci/golangci-lint to v1.18.0 as we face a lot of flakes with the new version.
See https://github.com/golangci/golangci-lint/issues/827.
Fixes #
```improvement operator
NONE
```
=> Revert golangci/golangci-lint to v1.18.0

controllers/provider-azure/charts/internal/cloud-provider-config/templates/cloud-provider-config.tpl, controllers/provider-azure/charts/internal/cloud-provider-config/values.yaml, controllers/provider-azure/pkg/controller/controlplane/valuesprovider.go, controllers/provider-azure/pkg/controller/controlplane/valuesprovider_test.go
Azure-CCM: Bundle cloudProviderRateLimitQPS[Write] to the maxNodes
Fixes #
https://github.com/kubernetes-sigs/cloud-provider-azure/issues/155#issuecomment-488523167
```improvement operator
An issue where cloud controller manager was self-rate-limited for azure shoot clusters with more than 10 nodes has been fixed.  
```
=> Azure-CCM: Bundle cloudProviderRateLimitQPS[Write] to the maxNodes

controllers/provider-alicloud/pkg/webhook/controlplaneexposure/ensurer.go, controllers/provider-alicloud/pkg/webhook/controlplaneexposure/ensurer_test.go, controllers/provider-aws/pkg/controller/controlplane/valuesprovider.go, controllers/provider-azure/pkg/webhook/controlplaneexposure/ensurer.go, controllers/provider-azure/pkg/webhook/controlplaneexposure/ensurer_test.go, controllers/provider-gcp/pkg/webhook/controlplaneexposure/ensurer.go, controllers/provider-gcp/pkg/webhook/controlplaneexposure/ensurer_test.go, controllers/provider-openstack/pkg/webhook/controlplaneexposure/ensurer.go, controllers/provider-openstack/pkg/webhook/controlplaneexposure/ensurer_test.go
This PR is needed to reconcile clusters whose `Kube-Apiserver` service was deleted when they were entering hibernation.
PR is still WIP for testing purposes.
```improvement operator
`Alicloud`, `AWS`, `Azure`, `GCP` and `OpenStack` providers are now capable of managing hibernated shoots which don't have a `Kube-Apiserver` service. 
```
=> Handle hibernated cluster w/ missing API service

controllers/provider-aws/charts/internal/aws-infra/templates/main.tf, controllers/provider-aws/charts/internal/aws-infra/values.yaml, controllers/provider-aws/docs/usage-as-end-user.md, controllers/provider-aws/example/30-infrastructure.yaml, controllers/provider-aws/hack/api-reference/api.md, controllers/provider-aws/pkg/apis/aws/types_infrastructure.go, controllers/provider-aws/pkg/apis/aws/v1alpha1/types_infrastructure.go, controllers/provider-aws/pkg/apis/aws/v1alpha1/zz_generated.conversion.go, controllers/provider-aws/pkg/apis/aws/v1alpha1/zz_generated.deepcopy.go, controllers/provider-aws/pkg/apis/aws/zz_generated.deepcopy.go, controllers/provider-aws/pkg/controller/infrastructure/actuator_reconcile.go
Added a new `enableECRAccess` flag to `aws.provider.extensions.gardener.cloud/v1alpha1.InfrastructureConfig` that allows to control whether the permissions shall be added to the AWS IAM role policy attached to all worker nodes.
Fixes #238
```noteworthy user
It is now possible to remove the ECR permission that is part of the AWS IAM role policy attached to all shoot worker nodes by specifying `aws.provider.extensions.gardener.cloud/v1alpha1.InfrastructureConfig.enableECRAccess=false`. If the field is not provided then it is defaulted to `true`, preserving the old behaviour where ECR access is always granted.
```
=> Allow to disable AWS ECR access via infrastructure config

pkg/controller/controlplane/reconciler.go
Fix a bug that was introduced with #472. The control plane controller sometimes preserves the `.status.lastError` in the `ControlPlane` resource although the reconciliation succeeded. This is undesired behaviour and is fixed now.
What #472 tried to introduce was a retry mechanism for status update (like done in all other controllers). Though, the semantics of the functions was changed, leading to the bug.
```improvement operator
NONE
```
=> Fix issue in cp ctrl that sometimes preserved last error

controllers/provider-alicloud/charts/internal/machineclass/templates/machineclass.yaml, controllers/provider-alicloud/charts/internal/machineclass/values.yaml, controllers/provider-alicloud/pkg/controller/worker/machines.go, controllers/provider-alicloud/pkg/controller/worker/machines_test.go, controllers/provider-aws/charts/internal/machineclass/templates/machineclass.yaml, controllers/provider-aws/charts/internal/machineclass/values.yaml, controllers/provider-aws/pkg/controller/worker/machines.go, controllers/provider-aws/pkg/controller/worker/machines_test.go, controllers/provider-azure/charts/internal/machineclass/templates/machineclass.yaml, controllers/provider-azure/charts/internal/machineclass/values.yaml, controllers/provider-azure/pkg/controller/worker/machines.go, controllers/provider-azure/pkg/controller/worker/machines_test.go, controllers/provider-gcp/charts/internal/machineclass/templates/machineclass.yaml, controllers/provider-gcp/charts/internal/machineclass/values.yaml, controllers/provider-gcp/pkg/controller/worker/machines.go, controllers/provider-gcp/pkg/controller/worker/machines_test.go, controllers/provider-openstack/charts/internal/machineclass/templates/machineclass.yaml, controllers/provider-openstack/charts/internal/machineclass/values.yaml, controllers/provider-openstack/pkg/controller/worker/machines.go, controllers/provider-openstack/pkg/controller/worker/machines_test.go, controllers/provider-packet/charts/internal/machineclass/templates/machineclass.yaml, controllers/provider-packet/charts/internal/machineclass/values.yaml, controllers/provider-packet/pkg/controller/worker/machines.go, controllers/provider-packet/pkg/controller/worker/machines_test.go, pkg/controller/worker/genericactuator/actuator.go
The machine class constant is now stored in the generic worker actuator package. The extensions now use it from there and expose the machine class labels as Helm chart values so that they can be properly injected.
Follow-up of https://github.com/gardener/gardener/pull/1804
```improvement operator
NONE
```
=> Use machineclass constant from generic worker actuator

Makefile
The networking-calico extension is missing the config flag after https://github.com/gardener/gardener-extensions/pull/541 in its `Makefile`. This PR adds the missing flag. 
```improvement operator
NONE
```
=> Fix networking-calico local dev

controllers/provider-gcp/charts/internal/machineclass/templates/machineclass.yaml, controllers/provider-gcp/charts/internal/machineclass/values.yaml, controllers/provider-gcp/pkg/controller/worker/machines.go, controllers/provider-gcp/pkg/controller/worker/machines_test.go
The `labels` field in the GCP machine class was already taken, but then we introduced `labels` again with https://github.com/gardener/gardener-extensions/pull/548 with led to conflicts. This PR fixes this.
/cc @hardikdr 
```improvement operator
NONE
```
=> Rename introduced labels to resourceLabels as labels is already taken

.dockerignore, .golangci.yaml, hack/check.sh, hack/install-requirements.sh
Currently we experience high memory usage for golangci-lint runs which most often breaks the ci/cd run.
With the current master branch and a local container with 5GB limit the `golangci-lint` is getting OOMKilled trying to consume almost all of the memory.
Several improvements:
- Update to golangci/golangci-lint to v1.20.1 which according to release notes has improved memory usage (ref https://github.com/golangci/golangci-lint/releases/tag/v1.20.0). (We don't update to the latest one because of the flakes we hit with it - ref #534).
- Disable the `unused` linter.
Fixes #
```improvement operator
NONE
```
=> Update golangci/golangci-lint to v1.20.1

controllers/extension-shoot-dns-service/charts/images.yaml
``` improvement operator github.com/gardener/external-dns-management #53 @MartinWeindel
fixing TXT record creation for bug introduced with v0.7.4
```
=> [ci:component:github.com/gardener/external-dns-management:v0.7.4->v0.7.5]

controllers/networking-calico/charts/images.yaml, controllers/networking-calico/charts/internal/calico/templates/node/clusterrole-calico-node.yaml, controllers/networking-calico/charts/internal/calico/templates/typha/deployment-calico-typha.yaml
Upgrade Calico to v3.11.2
```improvement operator
Calico now runs on version 3.11.2.
```
=> Upgrade Calico to v3.11.2

controllers/provider-gcp/pkg/controller/worker/machines.go, controllers/provider-gcp/pkg/controller/worker/machines_test.go
This PR completely removes support for public IPs in GCP. All egress traffic should be routed via CloudNAT. 
Fixes #408 
```noteworthy user
Support for public IPs is now completely removed and new machines will get no public IPs.
```
```action user
It is now mandatory to specify a CloudRouter configuration for GCP shoots (i.e., name) if a VPC is re-used. The Gardener landscape operator should ensure that this is done for all GCP shoots before updating to this version.
```
=> Remove support for public IPs in GCP

controllers/provider-aws/charts/validator-aws/charts/application/templates/validatingwebhook-validator.yaml
This PR adds v1beta1 shoots to the AWS webhook chart.
```noteworthy operator
The AWS validating webhook chart now also includes `v1beta1` shoots in group `core.gardener.cloud`.
```
=> Add v1beta1 shoots to AWS webhook chart

controllers/networking-calico/charts/internal/calico/templates/kube-controller/deployment-calico-kube-controllers.yaml, controllers/networking-calico/charts/internal/calico/templates/typha-cpha/deployment-calico-typha-horizontal-autoscaler.yaml, controllers/networking-calico/charts/internal/calico/templates/typha-cpva/deployment-calico-typha-vertical-autoscaler.yaml, controllers/networking-calico/charts/internal/calico/templates/typha/deployment-calico-typha.yaml
Add `origin:gardener` label to components deployed in the shoot by Gardener.
Prerequisite for gardener/gardener#1751  
```improvement operator
NONE
```
=> Add origin:gardener label

pkg/controller/healthcheck/reconciler.go
We don't need to log if the health checks were successful. Only errors are relevant.
```improvement operator
NONE
```
=> Increase log level for successful health checks

controllers/provider-openstack/charts/internal/machineclass/templates/machineclass.yaml, controllers/provider-openstack/charts/internal/machineclass/values.yaml, controllers/provider-openstack/example/30-worker.yaml, controllers/provider-openstack/pkg/controller/worker/machines.go
Added support for custom root disk size in OpenStack. 
/ref https://github.com/gardener/machine-controller-manager/pull/388
```improvement operator
Added support for custom root disk size in OpenStack
```
=> Added custom OpenStack root disk size

controllers/provider-alicloud/charts/images.yaml, controllers/provider-aws/charts/images.yaml, controllers/provider-azure/charts/images.yaml, controllers/provider-gcp/charts/images.yaml, controllers/provider-openstack/charts/images.yaml, controllers/provider-packet/charts/images.yaml, controllers/provider-vsphere/charts/images.yaml
``` noteworthy developer github.com/gardener/terraformer #33 @DockToFuture
The Google provider plugins have been upgraded to `v3.4.0`.
```
=> [ci:component:github.com/gardener/terraformer:0.17.0->0.18.0]

controllers/provider-alicloud/README.md, controllers/provider-aws/README.md, controllers/provider-azure/README.md, controllers/provider-gcp/README.md, controllers/provider-openstack/README.md
Add testgrid gardener 1.17 k8s e2e badges
```
NONE
```
=> Add testgrid gardener 1.17 k8s e2e badges

hack/generate-controller-registration.sh
Make `hack/generate-controller-registration.sh` work with helm 3.
Helm 3 does not have an `init` command, therefore `hack/generate-controller-registration.sh` fails, if the developer has helm 3 installed.
`helm init` is only now executed if version is <= 2.
```improvement developer
`hack/generate-controller-registration.sh` now works with helm 3.
```
=> Make hack/generate-controller-registration.sh work with helm 3

pkg/controller/worker/machines.go, pkg/controller/worker/machines_test.go
Need to give the provider extensions an option to add additional data to the worker pool hashs to control when worker pools machines need to be rolled due to infrastructure specific configurations.
See here: https://github.com/gardener/gardener-extensions/pull/586#issuecomment-580222938
```developer noteworthy
Extensions providers can now influence when machines of a worker pool need to be rolled in case there are specific needs.
```
=> Allow to extend workerpool hash with addional data

Makefile
Removes the `install` command from the Makefile
Fixes #590 
None
```noteworthy developer
Removed unnecessary `install` command from Makefile
```
=> Remove `install` command from Makefile

hack/generate-controller-registration.sh
Generate v1beta1 version of ControllerRegistrations instead of v1alpha1
Fixes #
```improvement developer
`hack/generate-controller-registration.sh` now generates ControllerRegistrations in version `v1beta1`. Please regenerate the ControllerRegistrations of your extensions.
```
=> Generate v1beta1 version of ControllerRegistrations

go.sum, pkg/mock/gardener-extensions/terraformer/mocks.go, pkg/terraformer/config.go, pkg/terraformer/terraformer.go, pkg/terraformer/types.go
As discussed in #597, the delete request fo DeadlineExceed Pod completes right away and the Pod is removed from the store, but the associated container on the Node runs/lives for `.spec.terminationGracePeriodSeconds` before it is SIGKILL-ed.
This PR removes `.spec.activeDeadlineSeconds` from the terraformer Pod spec to prevent the case described above.
Part of #597
```improvement operator
An issue causing running terraformer container to leak on the Node without associated Pod resource is now fixed. This will prevent multiple containers to execute `apply/destroy` commands simultaneously in some cases (especially for long running terraformer Pods).
```
=> Remove .spec.activeDeadlineSeconds from the terraformer Pod

go.sum, pkg/controller/worker/genericactuator/actuator_delete.go
Currently, user cannot change the cloud provider credentials which machine-controller-manager used during worker deletion: The credentials referenced by <CloudProviderType>MachineClass is updated during worker reconciliation, however, when a worker has DeletionTimestamp, it can not be reconciled any more.
By redeploying machineclasses during worker deletion, we can get the specific credentials up-to-date.
Fixes
- https://github.com/gardener/gardener-extension-provider-alicloud/issues/13
- https://github.com/gardener/gardener-extension-provider-aws/issues/19
- https://github.com/gardener/gardener-extension-provider-azure/issues/22
- https://github.com/gardener/gardener-extension-provider-gcp/issues/19
- …
=> update credentials during worker deletion

pkg/controller/operatingsystemconfig/oscommon/actuator/actuator_util.go, pkg/controller/operatingsystemconfig/oscommon/template/template_generator.go
Master is not building at all.
related #604 
```console
make verify
> Check
Executing check-generate
Executing golangci-lint
WARN [runner] Can't run linter unused: buildssa: analysis skipped: errors in package: [/go/go/src/github.com/gardener/gardener-extensions/pkg/controller/operatingsystemconfig/oscommon/actuator/actuator_util.go:74:36: config.Spec.CRIConfig undefined (type v1alpha1.OperatingSystemConfigSpec has no field or method CRIConfig) /go/go/src/github.com/gardener/gardener-extensions/pkg/controller/operatingsystemconfig/oscommon/actuator/actuator_util.go:74:68: config.Spec.CRIConfig undefined (type v1alpha1.OperatingSyste
mConfigSpec has no field or method CRIConfig) …
```
=> disable containerd until gardener is updated

CODEOWNERS
Add @gardener/test-infra-maintainers as CODEOWNERS for the `test` directory to enable them to easily merge test-related pull requests.
Fixes #
```improvement operator
NONE
```
=> Add test-infra-maintainers as CODEOWNERS

pkg/mock/gardener-extensions/webhook/controlplane/genericmutator/mocks.go, pkg/mock/gardener-extensions/webhook/mocks.go, pkg/webhook/controlplane/genericmutator/mutator.go, pkg/webhook/controlplane/genericmutator/mutator_test.go, pkg/webhook/controlplane/genericmutator/noopensurer.go, pkg/webhook/handler.go, pkg/webhook/handler_shootclient.go, pkg/webhook/handler_test.go, pkg/webhook/mutator.go, pkg/webhook/network/mutator.go
Mutators might be interested in the oldObject before the mutation. This old object is now passed to every single Ensurer. It is `nil` if the operation is `CREATE` and must always be checked.
Fixes # gardener/gardener#2048
This is still draft as it needs all other ensurers to get this implementation. 
```action developer
All methods of `pkg/webhook/controlplane/genericmutator.Ensurer` now have an additional argument which can optionally contain the old value of the object. If the admission request was `CREATE` this value is always `nil`.
```
=> Add old object to mutators

pkg/controller/cluster.go
This PR adds the `extensions.gardener.cloud/v1alpha1.Cluster.ObjectMeta` to the `controller.Cluster` struct. It is a prerequisite for the to-be-introduced CSI migration controller.
Part of gardener/gardener#2095
```improvement operator
NONE
```
=> Add Cluster object meta to controller.Cluster struct

pkg/controller/healthcheck/healtcheck_actuator.go
Prevent 
```
{"level":"dpanic","ts":"2020-03-29T10:19:33.773Z","logger":"aws-ControlPlane-healthcheck-actuator","msg":"odd number of arguments passed as key-value pairs for logging","ignored key":"ControlPlaneHealthy","stacktrace":"github.com/go-logr/zapr.handleFields\n\t/go/src/github.com/gardener/gardener-extension-provider-aws/vendor/github.com/go-logr/zapr/zapr.go:106\ngithub.com/go-logr/zapr.(*infoLogger).Info\n\t/go/src/github.com/gardener/gardener-extension-provider-aws/vendor/github.com/go-logr/zapr/zapr.go:70\ngithub.com/gardener/gardener-extensions/pkg/controller/healthcheck.(*Actuator).ExecuteHealthCheckFunctions.func1\n\t/go/src/github.com/gardener/gardener-extension-provider-aws/vendor/github.com/gardener/gardener-extensions/pkg/controll …
```
=> Fix even number of arguments for logger.Info() call
