gardener/gardener-extensions

pkg/controller/operatingsystemconfig/cmd.go
=> Fix controller option predicates

.ci/pipeline_definitions, .ci/prepare_release, Makefile, hack/check-generate.sh, hack/common.sh, hack/generate-controller-registration.sh, hack/generate.sh
Fix the build version coming via `EFFECTIVE_VERSION` from the pipeline.
```improvement operator
NONE
```
=> Fix build version

.ci/pipeline_definitions, .ci/prepare_release
Fix pipeline.
```improvement operator
NONE
```
=> Fix pipeline

.ci/prepare_release
Fix `prepare_release`
```improvement operator
NONE
```
=> Fix prepare_release script

.ci/prepare_release
Fix deletion of `REPO_DIR`
```improvement operator
NONE
```
=> Fix prepare release copy overwrite

.ci/pipeline_definitions
Fix pipeline target name for multi stage builds.
cc @rfranzke 
```improvement operator
NONE
```
=> Fix target name

hack/install-requirements.sh
Fix failing build due to new helm release
Fixes 
no issue created
```improvement operator
NONE
```
=> Fix failing build due to new helm release

.ci/prepare_release
Fix `pushd` / `podp` in `prepare_release` script.
```improvement operator
NONE
```
=> Fix pushd / popd

.ci/prepare_release
Fix `prepare-release`
```improvement operator
NONE
```
=> Fix prepare release

controllers/provider-aws/pkg/aws/types.go, controllers/provider-aws/pkg/controller/controlplane/actuator.go, controllers/provider-aws/pkg/webhook/controlplane/mutator.go, controllers/provider-aws/pkg/webhook/controlplaneexposure/mutator.go, pkg/webhook/controlplane/utils.go
Adds the actual implementation of AWS controlplane webhooks.
Based on #48, which should be merged first. Tests will follow in another PR.
```improvement operator
Implement AWS controlplane webhooks
```
=> Implement AWS controlplane webhooks

controllers/provider-alicloud/charts/images.yaml, controllers/provider-aws/charts/images.yaml, controllers/provider-azure/charts/images.yaml, controllers/provider-gcp/charts/images.yaml, controllers/provider-openstack/charts/images.yaml
``` noteworthy user github.com/gardener/terraformer #21 @deitch
The [Packet Terraform provider](https://github.com/terraform-providers/terraform-provider-packet) has been added.
```
=> [ci:component:github.com/gardener/terraformer:0.11.0->0.12.0]

controllers/provider-aws/charts/internal/cloud-controller-manager/templates/cloud-controller-manager.yaml, controllers/provider-aws/charts/internal/cloud-controller-manager/values.yaml, controllers/provider-aws/charts/internal/cloud-provider-config/templates/cloud-provider-config.yaml, controllers/provider-aws/charts/internal/cloud-provider-config/values.yaml, controllers/provider-aws/pkg/aws/types.go, controllers/provider-aws/pkg/controller/controlplane/controlplane_suite_test.go, controllers/provider-aws/pkg/controller/controlplane/valuesprovider.go, controllers/provider-aws/pkg/controller/controlplane/valuesprovider_test.go, controllers/provider-aws/pkg/controller/infrastructure/actuator_delete.go, controllers/provider-aws/pkg/controller/infrastructure/actuator_reconcile.go, controllers/provider-aws/pkg/controller/infrastructure/add.go, controllers/provider-azure/pkg/controller/infrastructure/add.go, controllers/provider-gcp/charts/internal/cloud-controller-manager/templates/cloud-controller-manager.yaml, controllers/provider-gcp/charts/internal/cloud-controller-manager/values.yaml, controllers/provider-gcp/charts/internal/cloud-provider-config/templates/cloud-provider-config.yaml, controllers/provider-gcp/charts/internal/cloud-provider-config/values.yaml, controllers/provider-gcp/pkg/controller/controlplane/controlplane_suite_test.go, controllers/provider-gcp/pkg/controller/controlplane/valuesprovider.go, controllers/provider-gcp/pkg/controller/controlplane/valuesprovider_test.go, controllers/provider-gcp/pkg/controller/infrastructure/add.go, controllers/provider-gcp/pkg/internal/apihelper/apihelper_suite_test.go, controllers/provider-gcp/pkg/internal/apihelper/subnet.go, controllers/provider-gcp/pkg/internal/apihelper/subnet_test.go, controllers/provider-openstack/pkg/controller/infrastructure/add.go
/cc @stoyanr
Several things can be "hard-coded" now that every provider has its own chart.
```improvement operator
NONE
```
=> Simplify AWS and GCP controlplane actuators

pkg/controller/infrastructure/controller.go
Enhances Infrastructure controller's `AddArgs` to include `WatchBuilder` argument which contains additional Watch controllers defined and passed by a provider.
=> Enhance Infrastructure controller with custom Watch controls

pkg/controller/worker/genericactuator/machine_crds.go
Add additionalPrinterColumns to MCM CRDs.
Fixes #
```improvement operator
kubectl does now show additional printer columns for MCM CRDs.
```
=> Add additionalPrinterColumns to MCM CRDs

controllers/provider-aws/pkg/webhook/controlplane/ensurer.go, controllers/provider-aws/pkg/webhook/controlplane/ensurer_test.go, controllers/provider-gcp/pkg/webhook/controlplane/ensurer.go, controllers/provider-gcp/pkg/webhook/controlplane/ensurer_test.go, pkg/mock/gardener-extensions/webhook/controlplane/genericmutator/mocks.go, pkg/webhook/controlplane/genericmutator/mutator.go, pkg/webhook/controlplane/genericmutator/mutator_test.go, pkg/webhook/controlplane/genericmutator/noopensurer.go
Enhance ControlPlane webhooks to do additional provider-specific modifications
Fixes #113 
```improvement operator
Enhance ControlPlane webhooks to do additional provider-specific modifications
```
=> Enhance controlplane webhooks to do more provider-specific modifications

controllers/provider-azure/charts/internal/cloud-provider-config/templates/cloud-provider-config.yaml, controllers/provider-azure/example/30-controlplane.yaml, controllers/provider-azure/pkg/controller/controlplane/valuesprovider.go, controllers/provider-azure/pkg/controller/controlplane/valuesprovider_test.go, controllers/provider-azure/pkg/webhook/controlplaneexposure/ensurer.go
Fixes a bug when retrieving configs from controlplane.infrastructurestatus
Updates the tests and examples
```improvement operator
NONE
```
=> Fix azure infra name retrieval

controllers/provider-alicloud/example/30-controlplane.yaml, controllers/provider-alicloud/pkg/apis/alicloud/types_controlplane.go, controllers/provider-alicloud/pkg/apis/alicloud/v1alpha1/types_controlplane.go, controllers/provider-alicloud/pkg/apis/alicloud/v1alpha1/zz_generated.conversion.go, controllers/provider-alicloud/pkg/controller/controlplane/valuesprovider.go, controllers/provider-alicloud/pkg/controller/controlplane/valuesprovider_test.go, controllers/provider-aws/example/30-controlplane.yaml, controllers/provider-aws/pkg/apis/aws/helper/helper.go, controllers/provider-aws/pkg/controller/controlplane/valuesprovider.go, controllers/provider-azure/example/30-controlplane.yaml, controllers/provider-gcp/example/30-controlplane.yaml, controllers/provider-gcp/pkg/apis/gcp/types_controlplane.go, controllers/provider-openstack/example/30-controlplane.yaml, controllers/provider-openstack/pkg/controller/controlplane/valuesprovider.go, controllers/provider-packet/example/30-controlplane.yaml
Fixes infra status retrieval for Alicloud and removes a TODO for AWS.
```improvement operator
NONE
```
=> Fix infra status retrieval for Alicloud

pkg/controller/controlplane/genericactuator/actuator.go
Removes possible sensitive information leaks in the logs.
```improvement operator
NONE
```
=> Remove sensitive info leaks

controllers/provider-gcp/pkg/controller/infrastructure/actuator_delete.go, controllers/provider-gcp/pkg/internal/infrastructure/infrastructure.go, controllers/provider-gcp/pkg/internal/infrastructure/infrastructure_test.go
This PR adds an additional check when deleting firewall rules which have `k8s` at the start of their name - now the TargetTags are checked if they include the shoot's controlplane namespace before the rules are added for deletion.
Fixes #158 
I've only ran the unit tests to check if this works.
```improvement operator
Deleting a shoot on GCP will now only delete the firewall rules for that shoot when multiple shoots share the same VPC network.
```
=> Fixes deletion of firewall rules on gcp

controllers/provider-gcp/pkg/controller/infrastructure/actuator_delete.go, controllers/provider-gcp/pkg/internal/infrastructure/infrastructure.go, controllers/provider-gcp/pkg/internal/infrastructure/infrastructure_test.go
When deleting a shoot cluster on GCP all routes in the same VPC network as the shoot cluster are also deleted. This PR adds an additional filter when chosing which routes to delete by checking if the route's NextHopInstance contains the shoot's seed namespace
Additional fix for #158. Routes on the same VPC were also affected by single cluster deletion
The names of routes can have equal prefixes if the shoot's seed namespaces are too long. Eg.: instead of `shoot--my-proj--test-shoot1` the prefix for the route name would only be `shoot--my-proj--test-shoot`. This is why I use the `NextHopInstance` url to determine if a route should be deleted.
```improvement user …
```
=> Fixes deletion of routes on GCP

pkg/controller/worker/genericactuator/actuator_reconcile.go
Most parts of the code in the generic worker actuator have been copied from the code in Gardener that was written over a year ago and before we started extensibility.
Back then when Gardener handled the machines it could delete the cluster-autoscaler deployment during a rolling update of worker machines because it knew that the task that would re-deploy the cluster-autoscaler would be executed after the rolling update has completed successfully.
Now, with extensibility, the reconciliation of the worker actuator and Gardener might not be in sync. Consequently, it might happen that the worker actuator reconciles and deletes  the cluster-autoscaler, but Gardener does not reconcile in order to bring it back (only later).
Let's improve the code such that …
=> Scale down/up cluster-autoscaler instead of deleting it

controllers/provider-aws/pkg/aws/client/client.go
Implement pagination for AWS ELB list calls.
/cc @schrodit 
```improvement operator
An issue that caused AWS infrastructure controller to not properly clean up remaining Kubernetes load balancers and security groups has been fixed.
```
=> Pagination for AWS ELB list call

pkg/controller/backupentry/genericactuator/actuator.go, pkg/controller/backupentry/genericactuator/actuator_test.go
Fixes #
```improvement user
Fix the backup entry extension bucketName propagation logic
```
=> Fix the backup entry actuator logic

Dockerfile, controllers/extension-certificate-service/README.md, controllers/extension-certificate-service/pkg/cmd/options.go, controllers/extension-certificate-service/pkg/controller/lifecycle/internal/chartvalues_test.go, controllers/networking-calico/README.md, controllers/networking-calico/pkg/apis/calico/v1alpha1/types_network.go, controllers/networking-calico/pkg/calico/types.go, controllers/os-coreos-alicloud/README.md, controllers/os-coreos/README.md, controllers/os-suse-jeos/README.md, controllers/os-ubuntu/README.md, controllers/provider-alicloud/README.md, controllers/provider-alicloud/pkg/webhook/controlplaneexposure/ensurer.go, controllers/provider-aws/README.md, controllers/provider-azure/README.md, controllers/provider-azure/pkg/webhook/controlplaneexposure/ensurer.go, controllers/provider-gcp/README.md, controllers/provider-gcp/pkg/webhook/controlplaneexposure/ensurer.go, controllers/provider-openstack/README.md, controllers/provider-openstack/pkg/webhook/controlplaneexposure/ensurer.go, controllers/provider-packet/README.md, pkg/controller/worker/machine_crds.go, pkg/inject/inject.go, pkg/predicate/predicate_test.go, pkg/webhook/registration.go
- Upgrade to golang:1.12.8
- Purge `dep` leftovers
Fixes #
```improvement operator
NONE
```
=> Minor nits

controllers/networking-calico/pkg/imagevector/imagevector.go
adds packr generate tag to image vector. 
```improvement operator
NONE
```
=> add packr generate tag to image vector

controllers/provider-alicloud/charts/images.yaml, controllers/provider-aws/charts/images.yaml, controllers/provider-azure/charts/images.yaml, controllers/provider-gcp/charts/images.yaml, controllers/provider-openstack/charts/images.yaml, controllers/provider-packet/charts/images.yaml
``` improvement operator github.com/gardener/machine-controller-manager #323 @prashanth26
Bugfix: Delete node object only if nodeName isn't empty
```
=> [ci:component:github.com/gardener/machine-controller-manager:0.21.0->0.21.1]

controllers/provider-gcp/pkg/webhook/controlplanebackup/ensurer.go
Do not add GCP backup secret to the `volumes` if not configured.
/cc @swapnilgm 
```improvement operator
NONE
```
=> Do not add GCP backup secret if not configured

pkg/controller/backupbucket/reconciler.go, pkg/controller/backupentry/reconciler.go
This PR put finalizer for secrets reffered by backupBucket and backupEntry resources.
Fixes #
```improvement operator
NONE
```
=> Put finalizer on referred secret by backup resources

go.mod, hack/tools.go
The workaround is no longer needed after #203.
Fixes #
```improvement operator
NONE
```
=> Clean tools.go

hack/install-requirements.sh
Update golangci-lint to v1.18.0 (requirement for golang-1.13).
Fixes #
```improvement operator
NONE
```
=> Update golangci-lint to v1.18.0

controllers/extension-certificate-service/pkg/controller/certservice/actuator.go, controllers/extension-shoot-dns-service/pkg/controller/actuator.go, controllers/networking-calico/pkg/controller/actuator_delete.go, pkg/controller/worker/genericactuator/machine_controller_manager.go
All other controllers are now also wait until their created `ManagedResource` are deleted in their deletion flow.
```improvement operator
The `networking-calico`, `extension-shoot-dns-service`, `extension-certificate-service`, and the generic `Worker` actuator now wait for their created ManagedResources to be deleted during their deletion flows. This is so that they don't accidentally remove their finalizers although created artefacts still exist. 
```
=> Wait until managed resources are deleted

controllers/provider-aws/pkg/controller/infrastructure/actuator_reconcile.go
Create awsClient when required.
/kind flake
Fixes #
```improvement operator
NONE
```
=> Create awsClient when required

controllers/provider-alicloud/charts/internal/machine-controller-manager/seed/templates/deployment.yaml, controllers/provider-aws/charts/internal/machine-controller-manager/seed/templates/deployment.yaml, controllers/provider-azure/charts/internal/machine-controller-manager/seed/templates/deployment.yaml, controllers/provider-gcp/charts/internal/machine-controller-manager/seed/templates/deployment.yaml, controllers/provider-openstack/charts/internal/machine-controller-manager/seed/templates/deployment.yaml, controllers/provider-packet/charts/internal/machine-controller-manager/seed/templates/deployment.yaml, pkg/webhook/controlplane/etcd.go
This is part of hvpa-controller integration into gardener.
Fixes #
Will remove the WIP tag once hvpa-controller perf tests are done.
```improvement operator
```
=> Changing limits for backup-restore container

controllers/provider-azure/charts/internal/azure-infra/templates/main.tf
Revert #331.
Ref https://github.com/terraform-providers/terraform-provider-azurerm/issues/3077#issuecomment-474364256
Fixes #
```improvement operator
Azure infrastructure can now be properly reconciled. Terraform does no longer finds diff after successful apply.
```
=> Revert "Azure: Update deprecated terraform resources"

go.mod, go.sum, vendor/github.com/gardener/gardener/pkg/utils/secrets/secrets.go, vendor/modules.txt
Ref gardener/gardener#1489.
Fixes #
```improvement operator
NONE
```
=> Vendor gardener/gardener@8493745aa2ee

controllers/provider-azure/pkg/controller/controlplane/valuesprovider.go
Concerning: https://concourse.ci.infra.gardener.cloud/teams/gardener/pipelines/gardener-extensions-release-0.13/jobs/release-0.13-head-update-job/builds/7
```improvement operator
NONE
```
=> Remove dead code

controllers/provider-azure/pkg/controller/controlplane/valuesprovider.go, hack/check.sh
/cc @ialidzhikov 
```improvement operator
NONE
```
=> Enable golangci checks

controllers/extension-shoot-cert-service/charts/internal/shoot-cert-management-seed/values.yaml
This PR raises the requests and limits for the `Cert-Management` controller.
```improvement operator
The resource limits and requests have been increased for the `Cert-Management` controller.
```
=> Raise resource requests/limits for cert-service

controllers/provider-alicloud/charts/internal/seed-controlplane/charts/alicloud-cloud-controller-manager/templates/_helpers.tpl, controllers/provider-alicloud/charts/internal/seed-controlplane/charts/alicloud-cloud-controller-manager/templates/vpa.yaml, controllers/provider-aws/charts/internal/cloud-controller-manager/templates/_helpers.tpl, controllers/provider-aws/charts/internal/cloud-controller-manager/templates/vpa.yaml, controllers/provider-azure/charts/internal/cloud-controller-manager/templates/_helpers.tpl, controllers/provider-azure/charts/internal/cloud-controller-manager/templates/vpa.yaml, controllers/provider-gcp/charts/internal/cloud-controller-manager/templates/_helpers.tpl, controllers/provider-gcp/charts/internal/cloud-controller-manager/templates/vpa.yaml, controllers/provider-openstack/charts/internal/cloud-controller-manager/templates/_helpers.tpl, controllers/provider-openstack/charts/internal/cloud-controller-manager/templates/vpa.yaml, controllers/provider-packet/charts/internal/seed-controlplane/charts/packet-cloud-controller-manager/templates/_helpers.tpl, controllers/provider-packet/charts/internal/seed-controlplane/charts/packet-cloud-controller-manager/templates/vpa.yaml
Add VPA for cloud-controller-managers 
Fixes #
```improvement operator
Add VPA for cloud-controller-managers 
```
=> add VPA for cloud-controller-managers

go.mod, go.sum, vendor/github.com/gardener/gardener/pkg/operation/terraformer/config.go, vendor/github.com/gardener/gardener/pkg/operation/terraformer/terraformer.go, vendor/modules.txt
Vendor github.com/gardener/gardener@9928f1a9ddd4
Fixes #
```improvement operator
NONE
```
=> Vendor github.com/gardener/gardener@9928f1a9ddd4

controllers/provider-azure/docs/usage-as-end-user.md
=> Azure: Fix end-user documentation

controllers/provider-aws/charts/internal/aws-lb-readvertiser/templates/aws-lb-readvertiser.yaml
On certain platforms, the requested resource will lead to Pod crash. Increase the request a bit to avoid such crash.
Fixes #
```improvement operator
```
@rfranzke
=> up the requested resources so it won't crash

controllers/provider-aws/charts/internal/aws-infra/templates/main.tf
Bastion host related ssh rules removed
Fixes: https://github.com/gardener/gardener-extensions/issues/343
```improvement operator
```
=> bastion host related ssh rules removed

Dockerfile, pkg/controller/status.go
Pass LastUpdateTime to LastErrors.
Fixes #388
```improvement operator
NONE
```
=> Pass LastUpdateTime to LastErrors

Dockerfile
```improvement operator
NONE
```
=> Update image version

controllers/networking-calico/charts/internal/calico/templates/typha-vertical-autoscaling-config.yaml
Cherry-pick of #456.
Fixes #454
```improvement operator
An issue preventing `calico-typha-vertical-autoscaler` to patch (scale) `calico-typha-deploy` is now fixed.
```
=> [release-1.0] Fix typha calico-typha-vertical-autoscaler

controllers/provider-aws/pkg/aws/client/client.go
This PR fixes the following error while deleting the backup entry. The error was observed for buckets with more than 1000 objects in entry. This is usually case when etcd-backup-restore has not yet deleted the old backups.
``` 
level=error msg="BackupEntry did not get deleted yet, lastError is: Error deleting backupentry: MalformedXML: The XML you provided was not well-formed or did not validate against our published schema\n\tstatus code: 400, request id: 7D4B2CD4448AA7A8,
```
Fixes #
```improvement operator
Fix the `backupEntry` deletion error in case of more than 1000 backups accumulated for …
```
=> Fix backup entry deletion for provider-aws

controllers/provider-alicloud/charts/images.yaml, controllers/provider-aws/charts/images.yaml, controllers/provider-azure/charts/images.yaml, controllers/provider-gcp/charts/images.yaml, controllers/provider-openstack/charts/images.yaml, controllers/provider-packet/charts/images.yaml
``` improvement operator github.com/gardener/terraformer #32 @MartinWeindel
added NSX-T Terraform provider for VMware vSphere
```
=> [ci:component:github.com/gardener/terraformer:0.16.0->0.17.0]

controllers/provider-alicloud/docs/usage-as-operator.md, controllers/provider-gcp/README.md
Ref gardener/gardener#1671
Fixes #
```improvement operator
NONE
```
=> Update provider-gcp README.md

controllers/extension-shoot-cert-service/charts/images.yaml
``` improvement operator github.com/gardener/cert-management #12 @MartinWeindel
improved behaviour if same certificate is requested multiple times simultaneously
```
=> [ci:component:github.com/gardener/cert-management:v0.2.9->v0.2.10]

controllers/provider-packet/charts/images.yaml
Fixes #
```improvement operator
```
=> use released versions for packethost

pkg/controller/worker/genericactuator/machine_controller_manager.go
Minor nit in error message.
Fixes #
```improvement operator
NONE
```
=> Minor nit in error message

controllers/extension-shoot-cert-service/charts/images.yaml
``` improvement operator github.com/gardener/cert-management #13 @MartinWeindel
Minor improvement for handling concurrent pending challenges.
More logging for troubleshooting.
```
=> [ci:component:github.com/gardener/cert-management:v0.2.10->v0.2.11]

controllers/provider-azure/charts/internal/azure-infra/templates/main.tf
Azure infrastructure creation fail frequently because Terraform can't calculate the dependency graph correctly. As of today it will still work after some retries, but this will be improved with this PR. 
The correct resource group references are now passed to the respective resources and should therefore prevent infra failures due to `ResourceGroupNotFound` errors.
Fixes #373
```improvement operator
Infrastructure creation and deletion are optimized for Azure.
```
=> Azure: Optimize infrastructure creation/deletion

controllers/extension-shoot-cert-service/charts/images.yaml
``` improvement operator github.com/gardener/cert-management #14 @MartinWeindel
keep existing labels and annotations in certificate secret
```
=> [ci:component:github.com/gardener/cert-management:v0.2.11->v0.2.13]

pkg/terraformer/config.go, pkg/terraformer/terraformer.go, pkg/terraformer/types.go, pkg/terraformer/waiter.go
Clean up deprecated funcs from pkg/terraformer.
Fixes #461
```improvement operator
NONE
```
=> Clean up deprecated funcs from pkg/terraformer

pkg/controller/healthcheck/actuator.go, pkg/controller/healthcheck/general/daemonset.go, pkg/controller/healthcheck/general/deployment.go, pkg/controller/healthcheck/general/managed_resource.go, pkg/controller/healthcheck/general/statefulsets.go, pkg/controller/healthcheck/healtcheck_actuator.go, pkg/controller/healthcheck/reconciler.go, pkg/controller/healthcheck/worker/sufficient_nodes.go
Wrong shoot client injection in the healthcheck library causes.
Fixes #
```improvement operator
```
=> fixing healthcheck wrong shoot client injection

controllers/networking-calico/charts/internal/calico/templates/kube-controller/deployment-calico-kube-controllers.yaml, controllers/networking-calico/charts/internal/calico/templates/typha-cpha/deployment-calico-typha-horizontal-autoscaler.yaml, controllers/networking-calico/charts/internal/calico/templates/typha-cpva/deployment-calico-typha-vertical-autoscaler.yaml, controllers/networking-calico/charts/internal/calico/templates/typha/deployment-calico-typha.yaml
This PR adds resources to Calico typha, kube-controllers, and cvpa. 
```improvement operator
None
```
=> Add missing resources for Calico components

controllers/provider-alicloud/docs/usage-as-operator.md, controllers/provider-aws/docs/usage-as-operator.md, controllers/provider-azure/docs/usage-as-operator.md, controllers/provider-gcp/docs/usage-as-operator.md, controllers/provider-openstack/docs/usage-as-operator.md, controllers/provider-packet/docs/usage-as-operator.md
Fix usage-as-operator.md docs to match the specs.
Fixes #
```improvement operator
NONE
```
=> Fix usage-as-operator.md docs to match the specs

controllers/provider-alicloud/charts/internal/shoot-system-components/charts/csi-alicloud/templates/csi-diskplugin-ds.yaml
Ensure csi components running on every nodes in Alicloud #578
Fixes #575
```improvement operator
In Alicloud, volumes could be attached on every node regardless taints.
```
=> Ensure csi components running on every nodes in Alicloud

controllers/provider-vsphere/cmd/gardener-extension-provider-vsphere/app/app.go, controllers/provider-vsphere/example/00-componentconfig.yaml, controllers/provider-vsphere/hack/api-reference/config.md, controllers/provider-vsphere/hack/generate-code, controllers/provider-vsphere/pkg/apis/config/types.go, controllers/provider-vsphere/pkg/apis/config/v1alpha1/types.go, controllers/provider-vsphere/pkg/apis/config/v1alpha1/zz_generated.conversion.go, controllers/provider-vsphere/pkg/apis/config/v1alpha1/zz_generated.deepcopy.go, controllers/provider-vsphere/pkg/apis/config/zz_generated.deepcopy.go, controllers/provider-vsphere/pkg/cmd/config.go, controllers/provider-vsphere/pkg/cmd/options.go, controllers/provider-vsphere/pkg/controller/controlplane/valuesprovider.go, controllers/provider-vsphere/pkg/controller/healthcheck/add.go, controllers/provider-vsphere/pkg/vsphere/types.go
healtcheck controller was missing for the new provider-vsphere
```improvement operator
```
=> provider-vsphere: added healthcheck controller

README.md
Add a list of known extension implementations to README.
Am I missing any known implementations?
```improvement operator
NONE
```
=> Add list of known extension implementations

hack/.ci/set_dependency_version
Adds the necessary lines of code to be able to process upgrade PR requests from external-dns-management
=> Update set_dependency_version for external-dns-management

pkg/controller/healthcheck/controller.go, pkg/controller/healthcheck/reconciler.go
Unify log keys to be lowercase.
```improvement operator
NONE
```
=> Unify log keys to be lowercase

pkg/webhook/certificates.go
Previously the extensions library would generate webhook certificates with a DNS SAN for the value of `--webhook-config-url` if `--webhook-config-mode=url`.
With this PR it adds an IP address SAN for the value of `--webhook-config-url` in case its a valid IP address instead of a DNS address SAN for it (which would lead to certificate issues when the webhook is called).
This is helpful if you want to run an extension webhook on your host machine and use it inside a local cluster, which can only reach to the host via an IP address (e.g. minikube).
```improvement developer
You can now pass an IP address to `--webhook-config-url` and the extensions library will …
```
=> Support IP address as --webhook-config-url

pkg/controller/operatingsystemconfig/oscommon/actuator/actuator_util.go, pkg/controller/operatingsystemconfig/oscommon/generator/generator.go, pkg/controller/operatingsystemconfig/oscommon/generator/test/template_generator.go, pkg/controller/operatingsystemconfig/oscommon/template/template_generator.go
Enablement of ContainerD according to GEP-10
Fixes #
NONE
=> GEP 10 - ContainerD Enablement

pkg/controller/worker/genericactuator/actuator_reconcile.go
With these changes, Gardener should be able to force delete machines whose deletion used to fail for pods with PDB violations in case of cluster hibernation. 
Fixes [MCM #415](https://github.com/gardener/machine-controller-manager/issues/415#issuecomment-593575152)
```improvement user
Allow force deletion of machines incase of cluster hibernation
```
=> Force delete machines incase of cluster hibernation

pkg/webhook/network/mutator.go
Fix nil check in network mutator.
/kind bug
Fixes #
```improvement operator
NONE
```
=> Fix nil check in network mutator

pkg/controller/worker/genericactuator/actuator_reconcile.go
The generic worker actuator does now only consider the wanted machine deployments when it waits for them to be ready. Also, when it cleans up unwanted machine deployments it now waits until they have been deleted from the system.
Fixes #623 
```improvement user
An issue in the machine reconciliation has been fixed that caused the reconciliation being stuck in some cases where a previously broken worker configuration (e.g., due to the specification of machine types that are not available in certain availability zones) has been corrected.
```
=> Fix bug preventing worker reconciliation in some cases
